{{- if eq .Values.authType "RHSSO" }}
apiVersion: v1
kind: Secret
metadata:
  name: rhacs-probe-rhsso-client-secret
  namespace: {{ .Values.namespace | quote }}
stringData:
  CLIENT_SECRET: {{ .Values.redHatSSO.clientSecret | quote }}
type: Opaque
{{- end }}
