{{- if eq .Values.authType "OCM" }}
apiVersion: v1
kind: Secret
metadata:
  name: rhacs-probe-ocm-token
  namespace: {{ .Values.namespace | quote }}
stringData:
  TOKEN: {{ .Values.ocm.token | quote }}
type: Opaque
{{- end }}
