apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: stackrox-operator-test-subscription
  namespace: "$STACKROX_OPERATOR_NAMESPACE"
spec:
  channel: $STACKROX_OPERATOR_CHANNEL
  name: rhacs-operator
  installPlanApproval: Manual
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: rhacs-operator.v${STACKROX_OPERATOR_VERSION}
  config:
    resources: $RHACS_OPERATOR_RESOURCES
