apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: stackrox-operator-test-subscription
  namespace: "$STACKROX_OPERATOR_NAMESPACE"
spec:
  channel: $STACKROX_OPERATOR_CHANNEL
  name: rhacs-operator
  installPlanApproval: Automatic
  source: stackrox-operator-test-index
  sourceNamespace: "$STACKROX_OPERATOR_NAMESPACE"
  config:
    env:
      # TODO(ROX-7740): Remove these once we have a single dev+CI repo.
      - name: ROX_OPERATOR_MAIN_REGISTRY
        value: "${IMAGE_REGISTRY}"
      - name: ROX_OPERATOR_COLLECTOR_REGISTRY
        value: "${IMAGE_REGISTRY}"
    resources: $RHACS_OPERATOR_RESOURCES
