version: "2"
run:
  go: 1.25.3
linters:
  default: none
  enable:
    - asciicheck
    # - bodyclose
    # - deadcode
    # - depguard
    # - dogsled
    # - dupl
    # - errcheck
    # - funlen
    # - gochecknoglobals
    # - gochecknoinits
    # - gocognit
    # - goconst
    - ginkgolinter
    - copyloopvar
    - gocritic
    # - gocyclo
    # - godot
    # - godox
    # - goerr113
    - revive
    # - gomnd
    # - goprintffuncname
    - gosec
    - govet
    - ineffassign
    # - interfacer
    # - lll
    # - maligned
    # - misspell
    # - nakedret
    # - nestif
    - nolintlint
    # - prealloc
    - rowserrcheck
    # - scopelint
    - staticcheck
    # - structcheck
    # - testpackage
    # - typecheck
    # - unconvert
    # - unparam
    - unused
    # - varcheck
    # - whitespace
    - wrapcheck
    # - wsl
  settings:
    gocritic:
      enabled-checks:
        - commentFormatting
    gosec:
      includes:
        - G601
    govet:
      disable:
        - shadow
        - fieldalignment
      enable-all: true
      settings:
        printf: # analyzer name, run `go tool vet help` to see all analyzers
          funcs: # run `go tool vet help printf` to see available settings for `printf` analyzer
            - Print
            - Printf
            - Println
            - Debug
            - Debugf
            - Info
            - Infof
            - Warn
            - Warnf
            - Error
            - Errorf
    nolintlint:
      allow-unused: false # report any unused nolint directives
      require-explanation: false # don't require an explanation for nolint directives
      require-specific: true # require nolint directives to be specific about which linter is being skipped
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
          arguments:
            - disableStutteringCheck
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
    # Disable specific staticcheck rules that were excluded in v1 config
    # staticcheck now includes both SA (staticcheck) and ST (stylecheck) rules
    staticcheck:
      checks:
        - all
        - -SA1019
        - -SA4001
        - -ST1000
        - -ST1001
        - -ST1003
        - -ST1005
        - -ST1016

  exclusions:
    generated: lax
    rules:
      - linters:
          - wrapcheck
        path: _test\.go
      # Ignore wrapcheck for the client, specifically within the RoundTripper.
      - linters:
          - wrapcheck
        path: pkg/client/fleetmanager/client.go
      - linters:
          - revive
        text: should have a package comment, unless it's in another file for this package
      - linters:
          - revive
        text: should not use dot imports
      - linters:
          - revive
        text: returns unexported type .* which can be annoying to use
      - linters:
          - revive
        text: error strings should not be capitalized or end with punctuation or a newline
      - linters:
          - revive
        text: should omit type int from declaration
      - linters:
          - revive
        text: don't use leading k in Go names
    paths:
      - .*_moq.go
      - internal/central/pkg/api/public
      - internal/central/pkg/api/private
      - internal/central/pkg/api/admin/private
      - pkg/client/redhatsso/api
      - emailsender/pkg/client/openapi
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
