FROM registry.access.redhat.com/ubi8/ubi-minimal:8.8

COPY \
    fleet-manager \
    fleetshard-sync \
    acsfleetctl \
    /usr/local/bin/

RUN curl -o /usr/bin/kubectl -LO "https://dl.k8s.io/release/v1.28.1/bin/linux/amd64/kubectl"
RUN chmod +x /usr/bin/kubectl

LABEL name="fleet-manager-tools" \
      vendor="Red Hat" \
      version="0.0.1" \
      summary="FleetManagerTools" \
      description="RHACS fleet-manager tools used for CI pipelines"
