kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: acsms-cluster
subjects:
  - kind: ServiceAccount
    name: default
    namespace: "$ACSMS_NAMESPACE"
roleRef:
  kind: ClusterRole
  name: acsms
  apiGroup: rbac.authorization.k8s.io
