/*
 * Red Hat Advanced Cluster Security Service Email Sender
 *
 * Red Hat Advanced Cluster Security (RHACS) Email Sender service allows sending email notification from ACS Central tenants without bringing an own SMTP service.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech). DO NOT EDIT.
package openapi

// Error struct for Error
type Error struct {
	Id          string `json:"id,omitempty"`
	Kind        string `json:"kind,omitempty"`
	Code        string `json:"code,omitempty"`
	Reason      string `json:"reason,omitempty"`
	OperationId string `json:"operation_id,omitempty"`
}
