/*
 * Red Hat Advanced Cluster Security Service Email Sender
 *
 * Red Hat Advanced Cluster Security (RHACS) Email Sender service allows sending email notification from ACS Central tenants without bringing an own SMTP service.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech). DO NOT EDIT.
package openapi

// SendEmailPayload Schema for the request body sent to /acscsemail POST
type SendEmailPayload struct {
	// a list of recipients to recieve an email
	To []string `json:"to"`
	// base64 encoded email content
	RawMessage string `json:"rawMessage"`
}
