// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package services

import (
	"context"
	"github.com/aws/aws-sdk-go/service/route53"
	"github.com/stackrox/acs-fleet-manager/internal/central/constants"
	"github.com/stackrox/acs-fleet-manager/internal/central/pkg/api/dbapi"
	"github.com/stackrox/acs-fleet-manager/internal/central/pkg/centrals/types"
	"github.com/stackrox/acs-fleet-manager/pkg/api"
	serviceError "github.com/stackrox/acs-fleet-manager/pkg/errors"
	"github.com/stackrox/acs-fleet-manager/pkg/services"
	"sync"
)

// Ensure, that CentralServiceMock does implement CentralService.
// If this is not the case, regenerate this file with moq.
var _ CentralService = &CentralServiceMock{}

// CentralServiceMock is a mock implementation of CentralService.
//
//	func TestSomethingThatUsesCentralService(t *testing.T) {
//
//		// make and configure a mocked CentralService
//		mockedCentralService := &CentralServiceMock{
//			AcceptCentralRequestFunc: func(centralRequest *dbapi.CentralRequest) *serviceError.ServiceError {
//				panic("mock out the AcceptCentralRequest method")
//			},
//			AssignClusterFunc: func(ctx context.Context, centralID string, clusterID string) *serviceError.ServiceError {
//				panic("mock out the AssignCluster method")
//			},
//			ChangeBillingParametersFunc: func(ctx context.Context, centralID string, billingModel string, cloudAccountID string, cloudProvider string, product string) *serviceError.ServiceError {
//				panic("mock out the ChangeBillingParameters method")
//			},
//			ChangeCentralCNAMErecordsFunc: func(centralRequest *dbapi.CentralRequest, action CentralRoutesAction) (*route53.ChangeResourceRecordSetsOutput, *serviceError.ServiceError) {
//				panic("mock out the ChangeCentralCNAMErecords method")
//			},
//			CountByRegionAndInstanceTypeFunc: func() ([]CentralRegionCount, error) {
//				panic("mock out the CountByRegionAndInstanceType method")
//			},
//			CountByStatusFunc: func(status []constants.CentralStatus) ([]CentralStatusCount, error) {
//				panic("mock out the CountByStatus method")
//			},
//			DeleteFunc: func(centralRequest *dbapi.CentralRequest, force bool) *serviceError.ServiceError {
//				panic("mock out the Delete method")
//			},
//			DeprovisionCentralForUsersFunc: func(users []string) *serviceError.ServiceError {
//				panic("mock out the DeprovisionCentralForUsers method")
//			},
//			DeprovisionExpiredCentralsFunc: func() *serviceError.ServiceError {
//				panic("mock out the DeprovisionExpiredCentrals method")
//			},
//			DetectInstanceTypeFunc: func(centralRequest *dbapi.CentralRequest) types.CentralInstanceType {
//				panic("mock out the DetectInstanceType method")
//			},
//			GetFunc: func(ctx context.Context, id string) (*dbapi.CentralRequest, *serviceError.ServiceError) {
//				panic("mock out the Get method")
//			},
//			GetByIDFunc: func(id string) (*dbapi.CentralRequest, *serviceError.ServiceError) {
//				panic("mock out the GetByID method")
//			},
//			GetCNAMERecordStatusFunc: func(centralRequest *dbapi.CentralRequest) (*CNameRecordStatus, error) {
//				panic("mock out the GetCNAMERecordStatus method")
//			},
//			HasAvailableCapacityInRegionFunc: func(centralRequest *dbapi.CentralRequest) (bool, *serviceError.ServiceError) {
//				panic("mock out the HasAvailableCapacityInRegion method")
//			},
//			ListFunc: func(ctx context.Context, listArgs *services.ListArguments) (dbapi.CentralList, *api.PagingMeta, *serviceError.ServiceError) {
//				panic("mock out the List method")
//			},
//			ListByStatusFunc: func(status ...constants.CentralStatus) ([]*dbapi.CentralRequest, *serviceError.ServiceError) {
//				panic("mock out the ListByStatus method")
//			},
//			ListCentralsWithRoutesNotCreatedFunc: func() ([]*dbapi.CentralRequest, *serviceError.ServiceError) {
//				panic("mock out the ListCentralsWithRoutesNotCreated method")
//			},
//			ListCentralsWithoutAuthConfigFunc: func() ([]*dbapi.CentralRequest, *serviceError.ServiceError) {
//				panic("mock out the ListCentralsWithoutAuthConfig method")
//			},
//			PrepareCentralRequestFunc: func(centralRequest *dbapi.CentralRequest) *serviceError.ServiceError {
//				panic("mock out the PrepareCentralRequest method")
//			},
//			RegisterCentralDeprovisionJobFunc: func(ctx context.Context, id string) *serviceError.ServiceError {
//				panic("mock out the RegisterCentralDeprovisionJob method")
//			},
//			RegisterCentralJobFunc: func(ctx context.Context, centralRequest *dbapi.CentralRequest) *serviceError.ServiceError {
//				panic("mock out the RegisterCentralJob method")
//			},
//			ResetCentralSecretBackupFunc: func(ctx context.Context, centralRequest *dbapi.CentralRequest) *serviceError.ServiceError {
//				panic("mock out the ResetCentralSecretBackup method")
//			},
//			RestoreFunc: func(ctx context.Context, id string) *serviceError.ServiceError {
//				panic("mock out the Restore method")
//			},
//			RotateCentralRHSSOClientFunc: func(ctx context.Context, centralRequest *dbapi.CentralRequest) *serviceError.ServiceError {
//				panic("mock out the RotateCentralRHSSOClient method")
//			},
//			UpdateIgnoreNilsFunc: func(centralRequest *dbapi.CentralRequest) *serviceError.ServiceError {
//				panic("mock out the UpdateIgnoreNils method")
//			},
//			UpdateStatusFunc: func(id string, status constants.CentralStatus) (bool, *serviceError.ServiceError) {
//				panic("mock out the UpdateStatus method")
//			},
//			UpdatesFunc: func(centralRequest *dbapi.CentralRequest, values map[string]interface{}) *serviceError.ServiceError {
//				panic("mock out the Updates method")
//			},
//			VerifyAndUpdateCentralAdminFunc: func(ctx context.Context, centralRequest *dbapi.CentralRequest) *serviceError.ServiceError {
//				panic("mock out the VerifyAndUpdateCentralAdmin method")
//			},
//		}
//
//		// use mockedCentralService in code that requires CentralService
//		// and then make assertions.
//
//	}
type CentralServiceMock struct {
	// AcceptCentralRequestFunc mocks the AcceptCentralRequest method.
	AcceptCentralRequestFunc func(centralRequest *dbapi.CentralRequest) *serviceError.ServiceError

	// AssignClusterFunc mocks the AssignCluster method.
	AssignClusterFunc func(ctx context.Context, centralID string, clusterID string) *serviceError.ServiceError

	// ChangeBillingParametersFunc mocks the ChangeBillingParameters method.
	ChangeBillingParametersFunc func(ctx context.Context, centralID string, billingModel string, cloudAccountID string, cloudProvider string, product string) *serviceError.ServiceError

	// ChangeCentralCNAMErecordsFunc mocks the ChangeCentralCNAMErecords method.
	ChangeCentralCNAMErecordsFunc func(centralRequest *dbapi.CentralRequest, action CentralRoutesAction) (*route53.ChangeResourceRecordSetsOutput, *serviceError.ServiceError)

	// CountByRegionAndInstanceTypeFunc mocks the CountByRegionAndInstanceType method.
	CountByRegionAndInstanceTypeFunc func() ([]CentralRegionCount, error)

	// CountByStatusFunc mocks the CountByStatus method.
	CountByStatusFunc func(status []constants.CentralStatus) ([]CentralStatusCount, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(centralRequest *dbapi.CentralRequest, force bool) *serviceError.ServiceError

	// DeprovisionCentralForUsersFunc mocks the DeprovisionCentralForUsers method.
	DeprovisionCentralForUsersFunc func(users []string) *serviceError.ServiceError

	// DeprovisionExpiredCentralsFunc mocks the DeprovisionExpiredCentrals method.
	DeprovisionExpiredCentralsFunc func() *serviceError.ServiceError

	// DetectInstanceTypeFunc mocks the DetectInstanceType method.
	DetectInstanceTypeFunc func(centralRequest *dbapi.CentralRequest) types.CentralInstanceType

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, id string) (*dbapi.CentralRequest, *serviceError.ServiceError)

	// GetByIDFunc mocks the GetByID method.
	GetByIDFunc func(id string) (*dbapi.CentralRequest, *serviceError.ServiceError)

	// GetCNAMERecordStatusFunc mocks the GetCNAMERecordStatus method.
	GetCNAMERecordStatusFunc func(centralRequest *dbapi.CentralRequest) (*CNameRecordStatus, error)

	// HasAvailableCapacityInRegionFunc mocks the HasAvailableCapacityInRegion method.
	HasAvailableCapacityInRegionFunc func(centralRequest *dbapi.CentralRequest) (bool, *serviceError.ServiceError)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, listArgs *services.ListArguments) (dbapi.CentralList, *api.PagingMeta, *serviceError.ServiceError)

	// ListByStatusFunc mocks the ListByStatus method.
	ListByStatusFunc func(status ...constants.CentralStatus) ([]*dbapi.CentralRequest, *serviceError.ServiceError)

	// ListCentralsWithRoutesNotCreatedFunc mocks the ListCentralsWithRoutesNotCreated method.
	ListCentralsWithRoutesNotCreatedFunc func() ([]*dbapi.CentralRequest, *serviceError.ServiceError)

	// ListCentralsWithoutAuthConfigFunc mocks the ListCentralsWithoutAuthConfig method.
	ListCentralsWithoutAuthConfigFunc func() ([]*dbapi.CentralRequest, *serviceError.ServiceError)

	// PrepareCentralRequestFunc mocks the PrepareCentralRequest method.
	PrepareCentralRequestFunc func(centralRequest *dbapi.CentralRequest) *serviceError.ServiceError

	// RegisterCentralDeprovisionJobFunc mocks the RegisterCentralDeprovisionJob method.
	RegisterCentralDeprovisionJobFunc func(ctx context.Context, id string) *serviceError.ServiceError

	// RegisterCentralJobFunc mocks the RegisterCentralJob method.
	RegisterCentralJobFunc func(ctx context.Context, centralRequest *dbapi.CentralRequest) *serviceError.ServiceError

	// ResetCentralSecretBackupFunc mocks the ResetCentralSecretBackup method.
	ResetCentralSecretBackupFunc func(ctx context.Context, centralRequest *dbapi.CentralRequest) *serviceError.ServiceError

	// RestoreFunc mocks the Restore method.
	RestoreFunc func(ctx context.Context, id string) *serviceError.ServiceError

	// RotateCentralRHSSOClientFunc mocks the RotateCentralRHSSOClient method.
	RotateCentralRHSSOClientFunc func(ctx context.Context, centralRequest *dbapi.CentralRequest) *serviceError.ServiceError

	// UpdateIgnoreNilsFunc mocks the UpdateIgnoreNils method.
	UpdateIgnoreNilsFunc func(centralRequest *dbapi.CentralRequest) *serviceError.ServiceError

	// UpdateStatusFunc mocks the UpdateStatus method.
	UpdateStatusFunc func(id string, status constants.CentralStatus) (bool, *serviceError.ServiceError)

	// UpdatesFunc mocks the Updates method.
	UpdatesFunc func(centralRequest *dbapi.CentralRequest, values map[string]interface{}) *serviceError.ServiceError

	// VerifyAndUpdateCentralAdminFunc mocks the VerifyAndUpdateCentralAdmin method.
	VerifyAndUpdateCentralAdminFunc func(ctx context.Context, centralRequest *dbapi.CentralRequest) *serviceError.ServiceError

	// calls tracks calls to the methods.
	calls struct {
		// AcceptCentralRequest holds details about calls to the AcceptCentralRequest method.
		AcceptCentralRequest []struct {
			// CentralRequest is the centralRequest argument value.
			CentralRequest *dbapi.CentralRequest
		}
		// AssignCluster holds details about calls to the AssignCluster method.
		AssignCluster []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// CentralID is the centralID argument value.
			CentralID string
			// ClusterID is the clusterID argument value.
			ClusterID string
		}
		// ChangeBillingParameters holds details about calls to the ChangeBillingParameters method.
		ChangeBillingParameters []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// CentralID is the centralID argument value.
			CentralID string
			// BillingModel is the billingModel argument value.
			BillingModel string
			// CloudAccountID is the cloudAccountID argument value.
			CloudAccountID string
			// CloudProvider is the cloudProvider argument value.
			CloudProvider string
			// Product is the product argument value.
			Product string
		}
		// ChangeCentralCNAMErecords holds details about calls to the ChangeCentralCNAMErecords method.
		ChangeCentralCNAMErecords []struct {
			// CentralRequest is the centralRequest argument value.
			CentralRequest *dbapi.CentralRequest
			// Action is the action argument value.
			Action CentralRoutesAction
		}
		// CountByRegionAndInstanceType holds details about calls to the CountByRegionAndInstanceType method.
		CountByRegionAndInstanceType []struct {
		}
		// CountByStatus holds details about calls to the CountByStatus method.
		CountByStatus []struct {
			// Status is the status argument value.
			Status []constants.CentralStatus
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// CentralRequest is the centralRequest argument value.
			CentralRequest *dbapi.CentralRequest
			// Force is the force argument value.
			Force bool
		}
		// DeprovisionCentralForUsers holds details about calls to the DeprovisionCentralForUsers method.
		DeprovisionCentralForUsers []struct {
			// Users is the users argument value.
			Users []string
		}
		// DeprovisionExpiredCentrals holds details about calls to the DeprovisionExpiredCentrals method.
		DeprovisionExpiredCentrals []struct {
		}
		// DetectInstanceType holds details about calls to the DetectInstanceType method.
		DetectInstanceType []struct {
			// CentralRequest is the centralRequest argument value.
			CentralRequest *dbapi.CentralRequest
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// GetByID holds details about calls to the GetByID method.
		GetByID []struct {
			// ID is the id argument value.
			ID string
		}
		// GetCNAMERecordStatus holds details about calls to the GetCNAMERecordStatus method.
		GetCNAMERecordStatus []struct {
			// CentralRequest is the centralRequest argument value.
			CentralRequest *dbapi.CentralRequest
		}
		// HasAvailableCapacityInRegion holds details about calls to the HasAvailableCapacityInRegion method.
		HasAvailableCapacityInRegion []struct {
			// CentralRequest is the centralRequest argument value.
			CentralRequest *dbapi.CentralRequest
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ListArgs is the listArgs argument value.
			ListArgs *services.ListArguments
		}
		// ListByStatus holds details about calls to the ListByStatus method.
		ListByStatus []struct {
			// Status is the status argument value.
			Status []constants.CentralStatus
		}
		// ListCentralsWithRoutesNotCreated holds details about calls to the ListCentralsWithRoutesNotCreated method.
		ListCentralsWithRoutesNotCreated []struct {
		}
		// ListCentralsWithoutAuthConfig holds details about calls to the ListCentralsWithoutAuthConfig method.
		ListCentralsWithoutAuthConfig []struct {
		}
		// PrepareCentralRequest holds details about calls to the PrepareCentralRequest method.
		PrepareCentralRequest []struct {
			// CentralRequest is the centralRequest argument value.
			CentralRequest *dbapi.CentralRequest
		}
		// RegisterCentralDeprovisionJob holds details about calls to the RegisterCentralDeprovisionJob method.
		RegisterCentralDeprovisionJob []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// RegisterCentralJob holds details about calls to the RegisterCentralJob method.
		RegisterCentralJob []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// CentralRequest is the centralRequest argument value.
			CentralRequest *dbapi.CentralRequest
		}
		// ResetCentralSecretBackup holds details about calls to the ResetCentralSecretBackup method.
		ResetCentralSecretBackup []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// CentralRequest is the centralRequest argument value.
			CentralRequest *dbapi.CentralRequest
		}
		// Restore holds details about calls to the Restore method.
		Restore []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// RotateCentralRHSSOClient holds details about calls to the RotateCentralRHSSOClient method.
		RotateCentralRHSSOClient []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// CentralRequest is the centralRequest argument value.
			CentralRequest *dbapi.CentralRequest
		}
		// UpdateIgnoreNils holds details about calls to the UpdateIgnoreNils method.
		UpdateIgnoreNils []struct {
			// CentralRequest is the centralRequest argument value.
			CentralRequest *dbapi.CentralRequest
		}
		// UpdateStatus holds details about calls to the UpdateStatus method.
		UpdateStatus []struct {
			// ID is the id argument value.
			ID string
			// Status is the status argument value.
			Status constants.CentralStatus
		}
		// Updates holds details about calls to the Updates method.
		Updates []struct {
			// CentralRequest is the centralRequest argument value.
			CentralRequest *dbapi.CentralRequest
			// Values is the values argument value.
			Values map[string]interface{}
		}
		// VerifyAndUpdateCentralAdmin holds details about calls to the VerifyAndUpdateCentralAdmin method.
		VerifyAndUpdateCentralAdmin []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// CentralRequest is the centralRequest argument value.
			CentralRequest *dbapi.CentralRequest
		}
	}
	lockAcceptCentralRequest             sync.RWMutex
	lockAssignCluster                    sync.RWMutex
	lockChangeBillingParameters          sync.RWMutex
	lockChangeCentralCNAMErecords        sync.RWMutex
	lockCountByRegionAndInstanceType     sync.RWMutex
	lockCountByStatus                    sync.RWMutex
	lockDelete                           sync.RWMutex
	lockDeprovisionCentralForUsers       sync.RWMutex
	lockDeprovisionExpiredCentrals       sync.RWMutex
	lockDetectInstanceType               sync.RWMutex
	lockGet                              sync.RWMutex
	lockGetByID                          sync.RWMutex
	lockGetCNAMERecordStatus             sync.RWMutex
	lockHasAvailableCapacityInRegion     sync.RWMutex
	lockList                             sync.RWMutex
	lockListByStatus                     sync.RWMutex
	lockListCentralsWithRoutesNotCreated sync.RWMutex
	lockListCentralsWithoutAuthConfig    sync.RWMutex
	lockPrepareCentralRequest            sync.RWMutex
	lockRegisterCentralDeprovisionJob    sync.RWMutex
	lockRegisterCentralJob               sync.RWMutex
	lockResetCentralSecretBackup         sync.RWMutex
	lockRestore                          sync.RWMutex
	lockRotateCentralRHSSOClient         sync.RWMutex
	lockUpdateIgnoreNils                 sync.RWMutex
	lockUpdateStatus                     sync.RWMutex
	lockUpdates                          sync.RWMutex
	lockVerifyAndUpdateCentralAdmin      sync.RWMutex
}

// AcceptCentralRequest calls AcceptCentralRequestFunc.
func (mock *CentralServiceMock) AcceptCentralRequest(centralRequest *dbapi.CentralRequest) *serviceError.ServiceError {
	if mock.AcceptCentralRequestFunc == nil {
		panic("CentralServiceMock.AcceptCentralRequestFunc: method is nil but CentralService.AcceptCentralRequest was just called")
	}
	callInfo := struct {
		CentralRequest *dbapi.CentralRequest
	}{
		CentralRequest: centralRequest,
	}
	mock.lockAcceptCentralRequest.Lock()
	mock.calls.AcceptCentralRequest = append(mock.calls.AcceptCentralRequest, callInfo)
	mock.lockAcceptCentralRequest.Unlock()
	return mock.AcceptCentralRequestFunc(centralRequest)
}

// AcceptCentralRequestCalls gets all the calls that were made to AcceptCentralRequest.
// Check the length with:
//
//	len(mockedCentralService.AcceptCentralRequestCalls())
func (mock *CentralServiceMock) AcceptCentralRequestCalls() []struct {
	CentralRequest *dbapi.CentralRequest
} {
	var calls []struct {
		CentralRequest *dbapi.CentralRequest
	}
	mock.lockAcceptCentralRequest.RLock()
	calls = mock.calls.AcceptCentralRequest
	mock.lockAcceptCentralRequest.RUnlock()
	return calls
}

// AssignCluster calls AssignClusterFunc.
func (mock *CentralServiceMock) AssignCluster(ctx context.Context, centralID string, clusterID string) *serviceError.ServiceError {
	if mock.AssignClusterFunc == nil {
		panic("CentralServiceMock.AssignClusterFunc: method is nil but CentralService.AssignCluster was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		CentralID string
		ClusterID string
	}{
		Ctx:       ctx,
		CentralID: centralID,
		ClusterID: clusterID,
	}
	mock.lockAssignCluster.Lock()
	mock.calls.AssignCluster = append(mock.calls.AssignCluster, callInfo)
	mock.lockAssignCluster.Unlock()
	return mock.AssignClusterFunc(ctx, centralID, clusterID)
}

// AssignClusterCalls gets all the calls that were made to AssignCluster.
// Check the length with:
//
//	len(mockedCentralService.AssignClusterCalls())
func (mock *CentralServiceMock) AssignClusterCalls() []struct {
	Ctx       context.Context
	CentralID string
	ClusterID string
} {
	var calls []struct {
		Ctx       context.Context
		CentralID string
		ClusterID string
	}
	mock.lockAssignCluster.RLock()
	calls = mock.calls.AssignCluster
	mock.lockAssignCluster.RUnlock()
	return calls
}

// ChangeBillingParameters calls ChangeBillingParametersFunc.
func (mock *CentralServiceMock) ChangeBillingParameters(ctx context.Context, centralID string, billingModel string, cloudAccountID string, cloudProvider string, product string) *serviceError.ServiceError {
	if mock.ChangeBillingParametersFunc == nil {
		panic("CentralServiceMock.ChangeBillingParametersFunc: method is nil but CentralService.ChangeBillingParameters was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		CentralID      string
		BillingModel   string
		CloudAccountID string
		CloudProvider  string
		Product        string
	}{
		Ctx:            ctx,
		CentralID:      centralID,
		BillingModel:   billingModel,
		CloudAccountID: cloudAccountID,
		CloudProvider:  cloudProvider,
		Product:        product,
	}
	mock.lockChangeBillingParameters.Lock()
	mock.calls.ChangeBillingParameters = append(mock.calls.ChangeBillingParameters, callInfo)
	mock.lockChangeBillingParameters.Unlock()
	return mock.ChangeBillingParametersFunc(ctx, centralID, billingModel, cloudAccountID, cloudProvider, product)
}

// ChangeBillingParametersCalls gets all the calls that were made to ChangeBillingParameters.
// Check the length with:
//
//	len(mockedCentralService.ChangeBillingParametersCalls())
func (mock *CentralServiceMock) ChangeBillingParametersCalls() []struct {
	Ctx            context.Context
	CentralID      string
	BillingModel   string
	CloudAccountID string
	CloudProvider  string
	Product        string
} {
	var calls []struct {
		Ctx            context.Context
		CentralID      string
		BillingModel   string
		CloudAccountID string
		CloudProvider  string
		Product        string
	}
	mock.lockChangeBillingParameters.RLock()
	calls = mock.calls.ChangeBillingParameters
	mock.lockChangeBillingParameters.RUnlock()
	return calls
}

// ChangeCentralCNAMErecords calls ChangeCentralCNAMErecordsFunc.
func (mock *CentralServiceMock) ChangeCentralCNAMErecords(centralRequest *dbapi.CentralRequest, action CentralRoutesAction) (*route53.ChangeResourceRecordSetsOutput, *serviceError.ServiceError) {
	if mock.ChangeCentralCNAMErecordsFunc == nil {
		panic("CentralServiceMock.ChangeCentralCNAMErecordsFunc: method is nil but CentralService.ChangeCentralCNAMErecords was just called")
	}
	callInfo := struct {
		CentralRequest *dbapi.CentralRequest
		Action         CentralRoutesAction
	}{
		CentralRequest: centralRequest,
		Action:         action,
	}
	mock.lockChangeCentralCNAMErecords.Lock()
	mock.calls.ChangeCentralCNAMErecords = append(mock.calls.ChangeCentralCNAMErecords, callInfo)
	mock.lockChangeCentralCNAMErecords.Unlock()
	return mock.ChangeCentralCNAMErecordsFunc(centralRequest, action)
}

// ChangeCentralCNAMErecordsCalls gets all the calls that were made to ChangeCentralCNAMErecords.
// Check the length with:
//
//	len(mockedCentralService.ChangeCentralCNAMErecordsCalls())
func (mock *CentralServiceMock) ChangeCentralCNAMErecordsCalls() []struct {
	CentralRequest *dbapi.CentralRequest
	Action         CentralRoutesAction
} {
	var calls []struct {
		CentralRequest *dbapi.CentralRequest
		Action         CentralRoutesAction
	}
	mock.lockChangeCentralCNAMErecords.RLock()
	calls = mock.calls.ChangeCentralCNAMErecords
	mock.lockChangeCentralCNAMErecords.RUnlock()
	return calls
}

// CountByRegionAndInstanceType calls CountByRegionAndInstanceTypeFunc.
func (mock *CentralServiceMock) CountByRegionAndInstanceType() ([]CentralRegionCount, error) {
	if mock.CountByRegionAndInstanceTypeFunc == nil {
		panic("CentralServiceMock.CountByRegionAndInstanceTypeFunc: method is nil but CentralService.CountByRegionAndInstanceType was just called")
	}
	callInfo := struct {
	}{}
	mock.lockCountByRegionAndInstanceType.Lock()
	mock.calls.CountByRegionAndInstanceType = append(mock.calls.CountByRegionAndInstanceType, callInfo)
	mock.lockCountByRegionAndInstanceType.Unlock()
	return mock.CountByRegionAndInstanceTypeFunc()
}

// CountByRegionAndInstanceTypeCalls gets all the calls that were made to CountByRegionAndInstanceType.
// Check the length with:
//
//	len(mockedCentralService.CountByRegionAndInstanceTypeCalls())
func (mock *CentralServiceMock) CountByRegionAndInstanceTypeCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockCountByRegionAndInstanceType.RLock()
	calls = mock.calls.CountByRegionAndInstanceType
	mock.lockCountByRegionAndInstanceType.RUnlock()
	return calls
}

// CountByStatus calls CountByStatusFunc.
func (mock *CentralServiceMock) CountByStatus(status []constants.CentralStatus) ([]CentralStatusCount, error) {
	if mock.CountByStatusFunc == nil {
		panic("CentralServiceMock.CountByStatusFunc: method is nil but CentralService.CountByStatus was just called")
	}
	callInfo := struct {
		Status []constants.CentralStatus
	}{
		Status: status,
	}
	mock.lockCountByStatus.Lock()
	mock.calls.CountByStatus = append(mock.calls.CountByStatus, callInfo)
	mock.lockCountByStatus.Unlock()
	return mock.CountByStatusFunc(status)
}

// CountByStatusCalls gets all the calls that were made to CountByStatus.
// Check the length with:
//
//	len(mockedCentralService.CountByStatusCalls())
func (mock *CentralServiceMock) CountByStatusCalls() []struct {
	Status []constants.CentralStatus
} {
	var calls []struct {
		Status []constants.CentralStatus
	}
	mock.lockCountByStatus.RLock()
	calls = mock.calls.CountByStatus
	mock.lockCountByStatus.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *CentralServiceMock) Delete(centralRequest *dbapi.CentralRequest, force bool) *serviceError.ServiceError {
	if mock.DeleteFunc == nil {
		panic("CentralServiceMock.DeleteFunc: method is nil but CentralService.Delete was just called")
	}
	callInfo := struct {
		CentralRequest *dbapi.CentralRequest
		Force          bool
	}{
		CentralRequest: centralRequest,
		Force:          force,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(centralRequest, force)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedCentralService.DeleteCalls())
func (mock *CentralServiceMock) DeleteCalls() []struct {
	CentralRequest *dbapi.CentralRequest
	Force          bool
} {
	var calls []struct {
		CentralRequest *dbapi.CentralRequest
		Force          bool
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// DeprovisionCentralForUsers calls DeprovisionCentralForUsersFunc.
func (mock *CentralServiceMock) DeprovisionCentralForUsers(users []string) *serviceError.ServiceError {
	if mock.DeprovisionCentralForUsersFunc == nil {
		panic("CentralServiceMock.DeprovisionCentralForUsersFunc: method is nil but CentralService.DeprovisionCentralForUsers was just called")
	}
	callInfo := struct {
		Users []string
	}{
		Users: users,
	}
	mock.lockDeprovisionCentralForUsers.Lock()
	mock.calls.DeprovisionCentralForUsers = append(mock.calls.DeprovisionCentralForUsers, callInfo)
	mock.lockDeprovisionCentralForUsers.Unlock()
	return mock.DeprovisionCentralForUsersFunc(users)
}

// DeprovisionCentralForUsersCalls gets all the calls that were made to DeprovisionCentralForUsers.
// Check the length with:
//
//	len(mockedCentralService.DeprovisionCentralForUsersCalls())
func (mock *CentralServiceMock) DeprovisionCentralForUsersCalls() []struct {
	Users []string
} {
	var calls []struct {
		Users []string
	}
	mock.lockDeprovisionCentralForUsers.RLock()
	calls = mock.calls.DeprovisionCentralForUsers
	mock.lockDeprovisionCentralForUsers.RUnlock()
	return calls
}

// DeprovisionExpiredCentrals calls DeprovisionExpiredCentralsFunc.
func (mock *CentralServiceMock) DeprovisionExpiredCentrals() *serviceError.ServiceError {
	if mock.DeprovisionExpiredCentralsFunc == nil {
		panic("CentralServiceMock.DeprovisionExpiredCentralsFunc: method is nil but CentralService.DeprovisionExpiredCentrals was just called")
	}
	callInfo := struct {
	}{}
	mock.lockDeprovisionExpiredCentrals.Lock()
	mock.calls.DeprovisionExpiredCentrals = append(mock.calls.DeprovisionExpiredCentrals, callInfo)
	mock.lockDeprovisionExpiredCentrals.Unlock()
	return mock.DeprovisionExpiredCentralsFunc()
}

// DeprovisionExpiredCentralsCalls gets all the calls that were made to DeprovisionExpiredCentrals.
// Check the length with:
//
//	len(mockedCentralService.DeprovisionExpiredCentralsCalls())
func (mock *CentralServiceMock) DeprovisionExpiredCentralsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockDeprovisionExpiredCentrals.RLock()
	calls = mock.calls.DeprovisionExpiredCentrals
	mock.lockDeprovisionExpiredCentrals.RUnlock()
	return calls
}

// DetectInstanceType calls DetectInstanceTypeFunc.
func (mock *CentralServiceMock) DetectInstanceType(centralRequest *dbapi.CentralRequest) types.CentralInstanceType {
	if mock.DetectInstanceTypeFunc == nil {
		panic("CentralServiceMock.DetectInstanceTypeFunc: method is nil but CentralService.DetectInstanceType was just called")
	}
	callInfo := struct {
		CentralRequest *dbapi.CentralRequest
	}{
		CentralRequest: centralRequest,
	}
	mock.lockDetectInstanceType.Lock()
	mock.calls.DetectInstanceType = append(mock.calls.DetectInstanceType, callInfo)
	mock.lockDetectInstanceType.Unlock()
	return mock.DetectInstanceTypeFunc(centralRequest)
}

// DetectInstanceTypeCalls gets all the calls that were made to DetectInstanceType.
// Check the length with:
//
//	len(mockedCentralService.DetectInstanceTypeCalls())
func (mock *CentralServiceMock) DetectInstanceTypeCalls() []struct {
	CentralRequest *dbapi.CentralRequest
} {
	var calls []struct {
		CentralRequest *dbapi.CentralRequest
	}
	mock.lockDetectInstanceType.RLock()
	calls = mock.calls.DetectInstanceType
	mock.lockDetectInstanceType.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *CentralServiceMock) Get(ctx context.Context, id string) (*dbapi.CentralRequest, *serviceError.ServiceError) {
	if mock.GetFunc == nil {
		panic("CentralServiceMock.GetFunc: method is nil but CentralService.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedCentralService.GetCalls())
func (mock *CentralServiceMock) GetCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// GetByID calls GetByIDFunc.
func (mock *CentralServiceMock) GetByID(id string) (*dbapi.CentralRequest, *serviceError.ServiceError) {
	if mock.GetByIDFunc == nil {
		panic("CentralServiceMock.GetByIDFunc: method is nil but CentralService.GetByID was just called")
	}
	callInfo := struct {
		ID string
	}{
		ID: id,
	}
	mock.lockGetByID.Lock()
	mock.calls.GetByID = append(mock.calls.GetByID, callInfo)
	mock.lockGetByID.Unlock()
	return mock.GetByIDFunc(id)
}

// GetByIDCalls gets all the calls that were made to GetByID.
// Check the length with:
//
//	len(mockedCentralService.GetByIDCalls())
func (mock *CentralServiceMock) GetByIDCalls() []struct {
	ID string
} {
	var calls []struct {
		ID string
	}
	mock.lockGetByID.RLock()
	calls = mock.calls.GetByID
	mock.lockGetByID.RUnlock()
	return calls
}

// GetCNAMERecordStatus calls GetCNAMERecordStatusFunc.
func (mock *CentralServiceMock) GetCNAMERecordStatus(centralRequest *dbapi.CentralRequest) (*CNameRecordStatus, error) {
	if mock.GetCNAMERecordStatusFunc == nil {
		panic("CentralServiceMock.GetCNAMERecordStatusFunc: method is nil but CentralService.GetCNAMERecordStatus was just called")
	}
	callInfo := struct {
		CentralRequest *dbapi.CentralRequest
	}{
		CentralRequest: centralRequest,
	}
	mock.lockGetCNAMERecordStatus.Lock()
	mock.calls.GetCNAMERecordStatus = append(mock.calls.GetCNAMERecordStatus, callInfo)
	mock.lockGetCNAMERecordStatus.Unlock()
	return mock.GetCNAMERecordStatusFunc(centralRequest)
}

// GetCNAMERecordStatusCalls gets all the calls that were made to GetCNAMERecordStatus.
// Check the length with:
//
//	len(mockedCentralService.GetCNAMERecordStatusCalls())
func (mock *CentralServiceMock) GetCNAMERecordStatusCalls() []struct {
	CentralRequest *dbapi.CentralRequest
} {
	var calls []struct {
		CentralRequest *dbapi.CentralRequest
	}
	mock.lockGetCNAMERecordStatus.RLock()
	calls = mock.calls.GetCNAMERecordStatus
	mock.lockGetCNAMERecordStatus.RUnlock()
	return calls
}

// HasAvailableCapacityInRegion calls HasAvailableCapacityInRegionFunc.
func (mock *CentralServiceMock) HasAvailableCapacityInRegion(centralRequest *dbapi.CentralRequest) (bool, *serviceError.ServiceError) {
	if mock.HasAvailableCapacityInRegionFunc == nil {
		panic("CentralServiceMock.HasAvailableCapacityInRegionFunc: method is nil but CentralService.HasAvailableCapacityInRegion was just called")
	}
	callInfo := struct {
		CentralRequest *dbapi.CentralRequest
	}{
		CentralRequest: centralRequest,
	}
	mock.lockHasAvailableCapacityInRegion.Lock()
	mock.calls.HasAvailableCapacityInRegion = append(mock.calls.HasAvailableCapacityInRegion, callInfo)
	mock.lockHasAvailableCapacityInRegion.Unlock()
	return mock.HasAvailableCapacityInRegionFunc(centralRequest)
}

// HasAvailableCapacityInRegionCalls gets all the calls that were made to HasAvailableCapacityInRegion.
// Check the length with:
//
//	len(mockedCentralService.HasAvailableCapacityInRegionCalls())
func (mock *CentralServiceMock) HasAvailableCapacityInRegionCalls() []struct {
	CentralRequest *dbapi.CentralRequest
} {
	var calls []struct {
		CentralRequest *dbapi.CentralRequest
	}
	mock.lockHasAvailableCapacityInRegion.RLock()
	calls = mock.calls.HasAvailableCapacityInRegion
	mock.lockHasAvailableCapacityInRegion.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *CentralServiceMock) List(ctx context.Context, listArgs *services.ListArguments) (dbapi.CentralList, *api.PagingMeta, *serviceError.ServiceError) {
	if mock.ListFunc == nil {
		panic("CentralServiceMock.ListFunc: method is nil but CentralService.List was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		ListArgs *services.ListArguments
	}{
		Ctx:      ctx,
		ListArgs: listArgs,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx, listArgs)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedCentralService.ListCalls())
func (mock *CentralServiceMock) ListCalls() []struct {
	Ctx      context.Context
	ListArgs *services.ListArguments
} {
	var calls []struct {
		Ctx      context.Context
		ListArgs *services.ListArguments
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// ListByStatus calls ListByStatusFunc.
func (mock *CentralServiceMock) ListByStatus(status ...constants.CentralStatus) ([]*dbapi.CentralRequest, *serviceError.ServiceError) {
	if mock.ListByStatusFunc == nil {
		panic("CentralServiceMock.ListByStatusFunc: method is nil but CentralService.ListByStatus was just called")
	}
	callInfo := struct {
		Status []constants.CentralStatus
	}{
		Status: status,
	}
	mock.lockListByStatus.Lock()
	mock.calls.ListByStatus = append(mock.calls.ListByStatus, callInfo)
	mock.lockListByStatus.Unlock()
	return mock.ListByStatusFunc(status...)
}

// ListByStatusCalls gets all the calls that were made to ListByStatus.
// Check the length with:
//
//	len(mockedCentralService.ListByStatusCalls())
func (mock *CentralServiceMock) ListByStatusCalls() []struct {
	Status []constants.CentralStatus
} {
	var calls []struct {
		Status []constants.CentralStatus
	}
	mock.lockListByStatus.RLock()
	calls = mock.calls.ListByStatus
	mock.lockListByStatus.RUnlock()
	return calls
}

// ListCentralsWithRoutesNotCreated calls ListCentralsWithRoutesNotCreatedFunc.
func (mock *CentralServiceMock) ListCentralsWithRoutesNotCreated() ([]*dbapi.CentralRequest, *serviceError.ServiceError) {
	if mock.ListCentralsWithRoutesNotCreatedFunc == nil {
		panic("CentralServiceMock.ListCentralsWithRoutesNotCreatedFunc: method is nil but CentralService.ListCentralsWithRoutesNotCreated was just called")
	}
	callInfo := struct {
	}{}
	mock.lockListCentralsWithRoutesNotCreated.Lock()
	mock.calls.ListCentralsWithRoutesNotCreated = append(mock.calls.ListCentralsWithRoutesNotCreated, callInfo)
	mock.lockListCentralsWithRoutesNotCreated.Unlock()
	return mock.ListCentralsWithRoutesNotCreatedFunc()
}

// ListCentralsWithRoutesNotCreatedCalls gets all the calls that were made to ListCentralsWithRoutesNotCreated.
// Check the length with:
//
//	len(mockedCentralService.ListCentralsWithRoutesNotCreatedCalls())
func (mock *CentralServiceMock) ListCentralsWithRoutesNotCreatedCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockListCentralsWithRoutesNotCreated.RLock()
	calls = mock.calls.ListCentralsWithRoutesNotCreated
	mock.lockListCentralsWithRoutesNotCreated.RUnlock()
	return calls
}

// ListCentralsWithoutAuthConfig calls ListCentralsWithoutAuthConfigFunc.
func (mock *CentralServiceMock) ListCentralsWithoutAuthConfig() ([]*dbapi.CentralRequest, *serviceError.ServiceError) {
	if mock.ListCentralsWithoutAuthConfigFunc == nil {
		panic("CentralServiceMock.ListCentralsWithoutAuthConfigFunc: method is nil but CentralService.ListCentralsWithoutAuthConfig was just called")
	}
	callInfo := struct {
	}{}
	mock.lockListCentralsWithoutAuthConfig.Lock()
	mock.calls.ListCentralsWithoutAuthConfig = append(mock.calls.ListCentralsWithoutAuthConfig, callInfo)
	mock.lockListCentralsWithoutAuthConfig.Unlock()
	return mock.ListCentralsWithoutAuthConfigFunc()
}

// ListCentralsWithoutAuthConfigCalls gets all the calls that were made to ListCentralsWithoutAuthConfig.
// Check the length with:
//
//	len(mockedCentralService.ListCentralsWithoutAuthConfigCalls())
func (mock *CentralServiceMock) ListCentralsWithoutAuthConfigCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockListCentralsWithoutAuthConfig.RLock()
	calls = mock.calls.ListCentralsWithoutAuthConfig
	mock.lockListCentralsWithoutAuthConfig.RUnlock()
	return calls
}

// PrepareCentralRequest calls PrepareCentralRequestFunc.
func (mock *CentralServiceMock) PrepareCentralRequest(centralRequest *dbapi.CentralRequest) *serviceError.ServiceError {
	if mock.PrepareCentralRequestFunc == nil {
		panic("CentralServiceMock.PrepareCentralRequestFunc: method is nil but CentralService.PrepareCentralRequest was just called")
	}
	callInfo := struct {
		CentralRequest *dbapi.CentralRequest
	}{
		CentralRequest: centralRequest,
	}
	mock.lockPrepareCentralRequest.Lock()
	mock.calls.PrepareCentralRequest = append(mock.calls.PrepareCentralRequest, callInfo)
	mock.lockPrepareCentralRequest.Unlock()
	return mock.PrepareCentralRequestFunc(centralRequest)
}

// PrepareCentralRequestCalls gets all the calls that were made to PrepareCentralRequest.
// Check the length with:
//
//	len(mockedCentralService.PrepareCentralRequestCalls())
func (mock *CentralServiceMock) PrepareCentralRequestCalls() []struct {
	CentralRequest *dbapi.CentralRequest
} {
	var calls []struct {
		CentralRequest *dbapi.CentralRequest
	}
	mock.lockPrepareCentralRequest.RLock()
	calls = mock.calls.PrepareCentralRequest
	mock.lockPrepareCentralRequest.RUnlock()
	return calls
}

// RegisterCentralDeprovisionJob calls RegisterCentralDeprovisionJobFunc.
func (mock *CentralServiceMock) RegisterCentralDeprovisionJob(ctx context.Context, id string) *serviceError.ServiceError {
	if mock.RegisterCentralDeprovisionJobFunc == nil {
		panic("CentralServiceMock.RegisterCentralDeprovisionJobFunc: method is nil but CentralService.RegisterCentralDeprovisionJob was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockRegisterCentralDeprovisionJob.Lock()
	mock.calls.RegisterCentralDeprovisionJob = append(mock.calls.RegisterCentralDeprovisionJob, callInfo)
	mock.lockRegisterCentralDeprovisionJob.Unlock()
	return mock.RegisterCentralDeprovisionJobFunc(ctx, id)
}

// RegisterCentralDeprovisionJobCalls gets all the calls that were made to RegisterCentralDeprovisionJob.
// Check the length with:
//
//	len(mockedCentralService.RegisterCentralDeprovisionJobCalls())
func (mock *CentralServiceMock) RegisterCentralDeprovisionJobCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockRegisterCentralDeprovisionJob.RLock()
	calls = mock.calls.RegisterCentralDeprovisionJob
	mock.lockRegisterCentralDeprovisionJob.RUnlock()
	return calls
}

// RegisterCentralJob calls RegisterCentralJobFunc.
func (mock *CentralServiceMock) RegisterCentralJob(ctx context.Context, centralRequest *dbapi.CentralRequest) *serviceError.ServiceError {
	if mock.RegisterCentralJobFunc == nil {
		panic("CentralServiceMock.RegisterCentralJobFunc: method is nil but CentralService.RegisterCentralJob was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		CentralRequest *dbapi.CentralRequest
	}{
		Ctx:            ctx,
		CentralRequest: centralRequest,
	}
	mock.lockRegisterCentralJob.Lock()
	mock.calls.RegisterCentralJob = append(mock.calls.RegisterCentralJob, callInfo)
	mock.lockRegisterCentralJob.Unlock()
	return mock.RegisterCentralJobFunc(ctx, centralRequest)
}

// RegisterCentralJobCalls gets all the calls that were made to RegisterCentralJob.
// Check the length with:
//
//	len(mockedCentralService.RegisterCentralJobCalls())
func (mock *CentralServiceMock) RegisterCentralJobCalls() []struct {
	Ctx            context.Context
	CentralRequest *dbapi.CentralRequest
} {
	var calls []struct {
		Ctx            context.Context
		CentralRequest *dbapi.CentralRequest
	}
	mock.lockRegisterCentralJob.RLock()
	calls = mock.calls.RegisterCentralJob
	mock.lockRegisterCentralJob.RUnlock()
	return calls
}

// ResetCentralSecretBackup calls ResetCentralSecretBackupFunc.
func (mock *CentralServiceMock) ResetCentralSecretBackup(ctx context.Context, centralRequest *dbapi.CentralRequest) *serviceError.ServiceError {
	if mock.ResetCentralSecretBackupFunc == nil {
		panic("CentralServiceMock.ResetCentralSecretBackupFunc: method is nil but CentralService.ResetCentralSecretBackup was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		CentralRequest *dbapi.CentralRequest
	}{
		Ctx:            ctx,
		CentralRequest: centralRequest,
	}
	mock.lockResetCentralSecretBackup.Lock()
	mock.calls.ResetCentralSecretBackup = append(mock.calls.ResetCentralSecretBackup, callInfo)
	mock.lockResetCentralSecretBackup.Unlock()
	return mock.ResetCentralSecretBackupFunc(ctx, centralRequest)
}

// ResetCentralSecretBackupCalls gets all the calls that were made to ResetCentralSecretBackup.
// Check the length with:
//
//	len(mockedCentralService.ResetCentralSecretBackupCalls())
func (mock *CentralServiceMock) ResetCentralSecretBackupCalls() []struct {
	Ctx            context.Context
	CentralRequest *dbapi.CentralRequest
} {
	var calls []struct {
		Ctx            context.Context
		CentralRequest *dbapi.CentralRequest
	}
	mock.lockResetCentralSecretBackup.RLock()
	calls = mock.calls.ResetCentralSecretBackup
	mock.lockResetCentralSecretBackup.RUnlock()
	return calls
}

// Restore calls RestoreFunc.
func (mock *CentralServiceMock) Restore(ctx context.Context, id string) *serviceError.ServiceError {
	if mock.RestoreFunc == nil {
		panic("CentralServiceMock.RestoreFunc: method is nil but CentralService.Restore was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockRestore.Lock()
	mock.calls.Restore = append(mock.calls.Restore, callInfo)
	mock.lockRestore.Unlock()
	return mock.RestoreFunc(ctx, id)
}

// RestoreCalls gets all the calls that were made to Restore.
// Check the length with:
//
//	len(mockedCentralService.RestoreCalls())
func (mock *CentralServiceMock) RestoreCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockRestore.RLock()
	calls = mock.calls.Restore
	mock.lockRestore.RUnlock()
	return calls
}

// RotateCentralRHSSOClient calls RotateCentralRHSSOClientFunc.
func (mock *CentralServiceMock) RotateCentralRHSSOClient(ctx context.Context, centralRequest *dbapi.CentralRequest) *serviceError.ServiceError {
	if mock.RotateCentralRHSSOClientFunc == nil {
		panic("CentralServiceMock.RotateCentralRHSSOClientFunc: method is nil but CentralService.RotateCentralRHSSOClient was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		CentralRequest *dbapi.CentralRequest
	}{
		Ctx:            ctx,
		CentralRequest: centralRequest,
	}
	mock.lockRotateCentralRHSSOClient.Lock()
	mock.calls.RotateCentralRHSSOClient = append(mock.calls.RotateCentralRHSSOClient, callInfo)
	mock.lockRotateCentralRHSSOClient.Unlock()
	return mock.RotateCentralRHSSOClientFunc(ctx, centralRequest)
}

// RotateCentralRHSSOClientCalls gets all the calls that were made to RotateCentralRHSSOClient.
// Check the length with:
//
//	len(mockedCentralService.RotateCentralRHSSOClientCalls())
func (mock *CentralServiceMock) RotateCentralRHSSOClientCalls() []struct {
	Ctx            context.Context
	CentralRequest *dbapi.CentralRequest
} {
	var calls []struct {
		Ctx            context.Context
		CentralRequest *dbapi.CentralRequest
	}
	mock.lockRotateCentralRHSSOClient.RLock()
	calls = mock.calls.RotateCentralRHSSOClient
	mock.lockRotateCentralRHSSOClient.RUnlock()
	return calls
}

// UpdateIgnoreNils calls UpdateIgnoreNilsFunc.
func (mock *CentralServiceMock) UpdateIgnoreNils(centralRequest *dbapi.CentralRequest) *serviceError.ServiceError {
	if mock.UpdateIgnoreNilsFunc == nil {
		panic("CentralServiceMock.UpdateIgnoreNilsFunc: method is nil but CentralService.UpdateIgnoreNils was just called")
	}
	callInfo := struct {
		CentralRequest *dbapi.CentralRequest
	}{
		CentralRequest: centralRequest,
	}
	mock.lockUpdateIgnoreNils.Lock()
	mock.calls.UpdateIgnoreNils = append(mock.calls.UpdateIgnoreNils, callInfo)
	mock.lockUpdateIgnoreNils.Unlock()
	return mock.UpdateIgnoreNilsFunc(centralRequest)
}

// UpdateIgnoreNilsCalls gets all the calls that were made to UpdateIgnoreNils.
// Check the length with:
//
//	len(mockedCentralService.UpdateIgnoreNilsCalls())
func (mock *CentralServiceMock) UpdateIgnoreNilsCalls() []struct {
	CentralRequest *dbapi.CentralRequest
} {
	var calls []struct {
		CentralRequest *dbapi.CentralRequest
	}
	mock.lockUpdateIgnoreNils.RLock()
	calls = mock.calls.UpdateIgnoreNils
	mock.lockUpdateIgnoreNils.RUnlock()
	return calls
}

// UpdateStatus calls UpdateStatusFunc.
func (mock *CentralServiceMock) UpdateStatus(id string, status constants.CentralStatus) (bool, *serviceError.ServiceError) {
	if mock.UpdateStatusFunc == nil {
		panic("CentralServiceMock.UpdateStatusFunc: method is nil but CentralService.UpdateStatus was just called")
	}
	callInfo := struct {
		ID     string
		Status constants.CentralStatus
	}{
		ID:     id,
		Status: status,
	}
	mock.lockUpdateStatus.Lock()
	mock.calls.UpdateStatus = append(mock.calls.UpdateStatus, callInfo)
	mock.lockUpdateStatus.Unlock()
	return mock.UpdateStatusFunc(id, status)
}

// UpdateStatusCalls gets all the calls that were made to UpdateStatus.
// Check the length with:
//
//	len(mockedCentralService.UpdateStatusCalls())
func (mock *CentralServiceMock) UpdateStatusCalls() []struct {
	ID     string
	Status constants.CentralStatus
} {
	var calls []struct {
		ID     string
		Status constants.CentralStatus
	}
	mock.lockUpdateStatus.RLock()
	calls = mock.calls.UpdateStatus
	mock.lockUpdateStatus.RUnlock()
	return calls
}

// Updates calls UpdatesFunc.
func (mock *CentralServiceMock) Updates(centralRequest *dbapi.CentralRequest, values map[string]interface{}) *serviceError.ServiceError {
	if mock.UpdatesFunc == nil {
		panic("CentralServiceMock.UpdatesFunc: method is nil but CentralService.Updates was just called")
	}
	callInfo := struct {
		CentralRequest *dbapi.CentralRequest
		Values         map[string]interface{}
	}{
		CentralRequest: centralRequest,
		Values:         values,
	}
	mock.lockUpdates.Lock()
	mock.calls.Updates = append(mock.calls.Updates, callInfo)
	mock.lockUpdates.Unlock()
	return mock.UpdatesFunc(centralRequest, values)
}

// UpdatesCalls gets all the calls that were made to Updates.
// Check the length with:
//
//	len(mockedCentralService.UpdatesCalls())
func (mock *CentralServiceMock) UpdatesCalls() []struct {
	CentralRequest *dbapi.CentralRequest
	Values         map[string]interface{}
} {
	var calls []struct {
		CentralRequest *dbapi.CentralRequest
		Values         map[string]interface{}
	}
	mock.lockUpdates.RLock()
	calls = mock.calls.Updates
	mock.lockUpdates.RUnlock()
	return calls
}

// VerifyAndUpdateCentralAdmin calls VerifyAndUpdateCentralAdminFunc.
func (mock *CentralServiceMock) VerifyAndUpdateCentralAdmin(ctx context.Context, centralRequest *dbapi.CentralRequest) *serviceError.ServiceError {
	if mock.VerifyAndUpdateCentralAdminFunc == nil {
		panic("CentralServiceMock.VerifyAndUpdateCentralAdminFunc: method is nil but CentralService.VerifyAndUpdateCentralAdmin was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		CentralRequest *dbapi.CentralRequest
	}{
		Ctx:            ctx,
		CentralRequest: centralRequest,
	}
	mock.lockVerifyAndUpdateCentralAdmin.Lock()
	mock.calls.VerifyAndUpdateCentralAdmin = append(mock.calls.VerifyAndUpdateCentralAdmin, callInfo)
	mock.lockVerifyAndUpdateCentralAdmin.Unlock()
	return mock.VerifyAndUpdateCentralAdminFunc(ctx, centralRequest)
}

// VerifyAndUpdateCentralAdminCalls gets all the calls that were made to VerifyAndUpdateCentralAdmin.
// Check the length with:
//
//	len(mockedCentralService.VerifyAndUpdateCentralAdminCalls())
func (mock *CentralServiceMock) VerifyAndUpdateCentralAdminCalls() []struct {
	Ctx            context.Context
	CentralRequest *dbapi.CentralRequest
} {
	var calls []struct {
		Ctx            context.Context
		CentralRequest *dbapi.CentralRequest
	}
	mock.lockVerifyAndUpdateCentralAdmin.RLock()
	calls = mock.calls.VerifyAndUpdateCentralAdmin
	mock.lockVerifyAndUpdateCentralAdmin.RUnlock()
	return calls
}
