/*
 * Dinosaur Service Fleet Manager Admin APIs
 *
 * The admin APIs for the fleet manager of Dinosaur service
 *
 * API version: 0.0.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package private

// List struct for List
type List struct {
	Kind           string `json:"kind"`
	NextPageCursor string `json:"next_page_cursor,omitempty"`
	Size           int32  `json:"size"`
}
