---
clusters:
  - name: docker-compose
    cluster_id: 1234567890abcdef1234567890abcdef
    cloud_provider: standalone
    region: standalone
    schedulable: true
    status: ready
    provider_type: standalone
    supported_instance_type: "eval,standard"
    cluster_dns: cluster.local
    central_instance_limit: 5
    available_central_operator_versions:
      - version: "0.1.0"
        ready: true
        central_versions:
          - version: "0.1.0"
