apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rhacs-cloudwatch-exporter
  namespace: {{ include "cloudwatch.namespace" . }}
spec:
  secretStoreRef:
    name: {{ .Values.global.secretStore.aws.secretsManagerSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: rhacs-cloudwatch-exporter
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID # pragma: allowlist secret
      remoteRef:
        key: "cloudwatch-exporter"
        property: aws_access_key_id
    - secretKey: AWS_SECRET_ACCESS_KEY # pragma: allowlist secret
      remoteRef:
        key: "cloudwatch-exporter"
        property: "aws_secret_access_key"
