apiVersion: v1
kind: Secret
metadata:
  name: rhacs-cloudwatch-exporter
  namespace: {{ include "cloudwatch.namespace" . }}
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.aws.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secretAccessKey | quote }}
type: Opaque
