// Code generated by fleetshard/pkg/central/reconciler/gen/main.go. DO NOT EDIT.
package reconciler

import (
	"k8s.io/apimachinery/pkg/runtime/schema"
)

var tenantChartResourceGVKs = []schema.GroupVersionKind{
	schema.GroupVersionKind{Group: "", Version: "v1", Kind: "ConfigMap"},
	schema.GroupVersionKind{Group: "apps", Version: "v1", Kind: "Deployment"},
	schema.GroupVersionKind{Group: "networking.k8s.io", Version: "v1", Kind: "NetworkPolicy"},
	schema.GroupVersionKind{Group: "", Version: "v1", Kind: "Service"},
}
