// Code generated by fleetshard/pkg/central/reconciler/gen/main.go. DO NOT EDIT.
package reconciler

import (
	"k8s.io/apimachinery/pkg/runtime/schema"
)

// tenantChartResourceGVKs is a list of GroupVersionKind that...
// - are present in the tenant-resources helm chart
// - were present in a previous version of the chart. A comment will indicate that manual removal from the list is required.
var tenantChartResourceGVKs = []schema.GroupVersionKind{
	schema.GroupVersionKind{Group: "autoscaling.k8s.io", Version: "v1", Kind: "VerticalPodAutoscaler"},
	schema.GroupVersionKind{Group: "networking.k8s.io", Version: "v1", Kind: "NetworkPolicy"},
}
