apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhacs-external-secrets
  namespace: "$ARGOCD_NAMESPACE"
spec:
  destination:
    namespace: rhacs-external-secrets
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: "$ARGOCD_NAMESPACE"
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.14.4
    helm:
      valuesObject:
        image:
          repository: quay.io/app-sre/external-secrets
          tag: v0.14.4
        webhook:
          image:
            repository: quay.io/app-sre/external-secrets
            tag: v0.14.4
        certController:
          image:
            repository: quay.io/app-sre/external-secrets
            tag: v0.14.4
