kind: Secret
apiVersion: v1
metadata:
  name: rhacs-observatorium
  namespace: {{ include "observability.namespace" . }}
stringData:
  tenant: {{ .Values.observatorium.tenant | quote }}
  gateway: {{ .Values.observatorium.gateway | quote }}
  authType: {{ .Values.observatorium.authType | quote }}
  redHatSsoAuthServerUrl: {{ .Values.observatorium.redHatSsoAuthServerUrl | quote }}
  redHatSsoRealm: {{ .Values.observatorium.redHatSsoRealm | quote }}
  metricsClientId: {{ .Values.observatorium.metricsClientId | quote }}
  metricsSecret: {{ .Values.observatorium.metricsSecret | quote }}
type: Opaque
