apiVersion: v1
kind: Secret
metadata:
  name: rhacs-dead-mans-switch
  namespace: {{ include "observability.namespace" . }}
stringData:
  SNITCH_URL: {{ .Values.deadMansSwitch.url | quote }}
type: Opaque
