apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rhacs-observatorium
  namespace: {{ include "observability.namespace" . }}
spec:
  secretStoreRef:
    name: {{ .Values.global.secretStore.aws.secretsManagerSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: rhacs-observatorium
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        tenant: {{ .Values.observatorium.tenant | quote }}
        authType: {{ .Values.observatorium.authType | quote }}
        redHatSsoAuthServerUrl: {{ .Values.observatorium.redHatSsoAuthServerUrl | quote }}
        redHatSsoRealm: {{ .Values.observatorium.redHatSsoRealm | quote }}
        gateway: {{ .Values.observatorium.gateway | quote }}
        metricsClientId: {{ printf "'{{ .metrics_client_id }}'" }}
        metricsSecret: {{ printf "'{{ .metrics_secret }}'" }}
  data:
    - secretKey: metrics_client_id # pragma: allowlist secret
      remoteRef:
        key: "observability"
        property: "observatorium_metrics_client_id"
    - secretKey: metrics_secret # pragma: allowlist secret
      remoteRef:
        key: "observability"
        property: "observatorium_metrics_secret"
