kind: Secret
apiVersion: v1
metadata:
  name: rhacs-observatorium
  namespace: {{ include "observability.namespace" . }}
stringData:
  tenant: {{ .Values.observatorium.tenant | default "rhacs" | quote }}
  authType: {{ .Values.observatorium.authType | default "redhat" | quote }}
  redHatSsoAuthServerUrl: {{ .Values.observatorium.redHatSsoAuthServerUrl | default "https://sso.redhat.com/auth/" | quote }}
  redHatSsoRealm: {{ .Values.observatorium.redHatSsoRealm | default "redhat-external" | quote }}
  gateway: {{ .Values.observatorium.gateway | quote }}
  metricsClientId: {{ .Values.observatorium.metricsClientId | quote }}
  metricsSecret: {{ .Values.observatorium.metricsSecret | quote }}
type: Opaque
