apiVersion: v1
kind: Secret
metadata:
  name: rhacs-observability-configuration
  namespace: {{ include "observability.namespace" . }}
  labels:
    configures: observability-operator
stringData:
  access_token: {{ .Values.github.accessToken | quote }}
  repository: {{ .Values.github.repository | quote }}
  tag: {{ .Values.github.tag | quote }}
  channel: 'resources'
type: Opaque
