apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: external-dns-operator
  namespace: external-dns-operator
spec:
  targetNamespaces:
    - external-dns-operator
  upgradeStrategy: Default
