# This values file is used to render emailsender related kubernetes resources
# in context of emailsender <> central compatiblity tests. Values that are not
# below the emailsender field are the minimum required values for the helm chart
fleetshardSync:
  clusterName: test
  clusterId: test
  environment: dev
  managedDB:
    enabled: false
    subnetGroup: "dummyGroup"
emailsender:
  db:
    sslMode: "disable"
    caCertPath: ""
  image:
    repo: "quay.io/rhacs-eng/emailsender"
  enabled: true
  enableHTTPS: false
  clusterName: test
  replicas: 1
  authConfigFromKubernetes: true
secured-cluster:
  clusterName: test
  centralEndpoint: dummyEndpoint
