apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: emailsender-db-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: {{ .Values.global.secretStore.aws.secretsManagerSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: emailsender-db
    creationPolicy: Owner
  data:
    - secretKey: username # pragma: allowlist secret
      remoteRef:
        key: "cluster-{{ .Values.emailsender.clusterName }}-emailsender-db"
        property: "username"
    - secretKey: databaseName # pragma: allowlist secret
      remoteRef:
        key: "cluster-{{ .Values.emailsender.clusterName }}-emailsender-db"
        property: "databaseName"
    - secretKey: host # pragma: allowlist secret
      remoteRef:
        key: "cluster-{{ .Values.emailsender.clusterName }}-emailsender-db"
        property: "host"
    - secretKey: password # pragma: allowlist secret
      remoteRef:
        key: "cluster-{{ .Values.emailsender.clusterName }}-emailsender-db"
        property: "password" # pragma: allowlist secret
    - secretKey: port # pragma: allowlist secret
      remoteRef:
        key: "cluster-{{ .Values.emailsender.clusterName }}-emailsender-db"
        property: "port"
