apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: emailsender-ext-parameters
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: {{ .Values.global.secretStore.aws.parameterStoreSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: emailsender-parameters
    creationPolicy: Owner
  data:
    - secretKey: aws-role-arn # pragma: allowlist secret
      remoteRef:
        key: "/emailsender/aws_role_arn"
