{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: secrets-manager-secret-store
  namespace: external-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.externalSecrets.aws.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fleetshard-sync-ext-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: secrets-manager-secret-store
    kind: ClusterSecretStore
  target:
    name: fleetshard-sync
    creationPolicy: Owner
  data:
    - secretKey: rhsso-service-account-client-id # pragma: allowlist secret
      remoteRef:
        key: "fleetshard-sync"
        property: "rhsso_service_account_client_id"
    - secretKey: rhsso-service-account-client-secret # pragma: allowlist secret
      remoteRef:
        key: "fleetshard-sync"
        property: "rhsso_service_account_client_secret"
    - secretKey: telemetry-storage-key # pragma: allowlist secret
      remoteRef:
        key: "fleetshard-sync"
        property: "telemetry_storage_key"
{{- end }}
