apiVersion: v1
kind: ServiceAccount
metadata:
  name: fleetshard-sync
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fleetshard-sync-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fleetshard-sync-role
subjects:
- kind: ServiceAccount
  name: fleetshard-sync
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fleetshard-sync-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
