apiVersion: v1
kind: Secret
metadata:
  name: fleetshard-sync-rds-ca-bundle
  namespace: {{ .Release.Namespace }}
  labels:
    app: fleetshard-sync
stringData:
  rds-ca-bundle.pem: |-
    {{- .Files.Get .Values.fleetshardSync.aws.rdsCertsBundle | nindent 4 }}
