apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  annotations:
    kubernetes.io/description: ephemeral allows pods to use the node's ephemeral storage.
  name: ephemeral-volumes
volumes:
  - ephemeral
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
