apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  annotations:
    kubernetes.io/description: custom-acscs-ephemeral-volumes allows pods to use the node's ephemeral storage. This is needed until the clusters are upgraded to 4.12 where the anyuid SCC allows using ephemeral volumes by default
  name: custom-acscs-ephemeral-volumes
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
fsGroup:
  type: RunAsAny
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: false
readOnlyRootFilesystem: false
allowPrivilegeEscalation: true
requiredDropCapabilities:
  - MKNOD
supplementalGroups:
  type: RunAsAny
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret
  - ephemeral
