apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  annotations:
    kubernetes.io/description: ephemeral-volumes allows pods to use ephemeral volumes
  name: ephemeral-volumes
volumes:
  - ephemeral
