{{- define "aws.auth" -}}
auth:
  {{- if .Values.secretStore.aws.enableTokenAuth }}
  jwt:
    serviceAccountRef:
      name: {{ index .Values "external-secrets" "fullnameOverride" }}
      namespace: {{ .Release.Namespace }}
  {{- else }}
  secretRef:
    accessKeyIDSecretRef:
      name: {{ .Values.secretStore.aws.secretName }}
      key: access-key-id
    secretAccessKeySecretRef:
      name: {{ .Values.secretStore.aws.secretName }}
      key: secret-access-key
  {{- end }}
{{- end -}}

{{- if not .Values.secretStore.aws.enableTokenAuth }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretStore.aws.secretName }}
  namespace: {{ .Release.Namespace }}
stringData:
  access-key-id: {{ .Values.secretStore.aws.accessKeyId | quote }}
  secret-access-key: {{ .Values.secretStore.aws.secretAccessKey | quote }}
type: Opaque
{{- end }}
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.secretStore.aws.secretsManagerSecretStoreName }}
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.secretStore.aws.region }}
{{ include "aws.auth" . | indent 6 }}
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.secretStore.aws.parameterStoreSecretStoreName }}
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    aws:
      service: ParameterStore
      region: {{ .Values.secretStore.aws.region }}
{{ include "aws.auth" . | indent 6 }}
