name: Setup OCM CLI
description: "Setup OCM command line tool"
inputs:
  version:
    description: "ocm version"
    default: v0.1.70
  client_id:
    description: "service account client id"
    required: true
  client_secret:
    description: "service account client secret"
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup external binaries cache
      uses: actions/cache@v3
      with:
        path: ~/.local/bin
        key: ocm-${{ inputs.version }}
    - name: Ensure OCM CLI is installed
      run: |
        INSTALL_DIR=${HOME}/.local/bin
        if [[ -f ${INSTALL_DIR}/ocm ]]; then
          echo "OCM already installed in ${INSTALL_DIR}/ocm"
        else
          echo "Installing ocm in ${INSTALL_DIR}/ocm"
          mkdir -p ${INSTALL_DIR}
          DOWNLOAD_URL="https://github.com/openshift-online/ocm-cli/releases/download/${{ inputs.version }}/ocm-linux-amd64"
          curl -sL "${DOWNLOAD_URL}" > ${INSTALL_DIR}/ocm
          chmod +x ${INSTALL_DIR}/ocm
        fi

        echo "$HOME/.local/bin" >> $GITHUB_PATH
        echo "OCM version: $(ocm version)"
      shell: bash
    - name: OCM login
      env:
        CLIENT_ID: ${{ inputs.client_id }}
        CLIENT_SECRET: ${{ inputs.client_secret }}
      run: |
        ocm login --client-id "${CLIENT_ID}" --client-secret "${CLIENT_SECRET}"
      shell: bash
