apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudwatch
  namespace: openshift-logging
spec:
  secretStoreRef:
    name: {{ .Values.global.secretStore.aws.secretsManagerSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: cloudwatch
    creationPolicy: Owner
  data:
    - secretKey: aws_access_key_id # pragma: allowlist secret
      remoteRef:
        key: "logging"
        property: "aws_access_key_id"
    - secretKey: aws_secret_access_key # pragma: allowlist secret
      remoteRef:
        key: "logging"
        property: "aws_secret_access_key"
