apiVersion: v1
kind: Secret
metadata:
  name: cloudwatch
  namespace: openshift-logging
data:
  aws_access_key_id: {{ .Values.aws.accessKeyId | b64enc | quote }}
  aws_secret_access_key: {{ .Values.aws.secretAccessKey | b64enc | quote }}
