apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
  annotations:
    # Add custom resource last.
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
spec:
  outputs:
    - name: cloudwatch-output
      type: cloudwatch
      cloudwatch:
        groupBy: "logType"
        groupPrefix: {{ .Values.groupPrefix | quote }}
        region: {{ .Values.aws.region | quote }}
      secret:
        name: cloudwatch
  pipelines:
    - name: data-plane-logs
      inputRefs:
        - infrastructure
        - audit
        - application
      outputRefs:
        - cloudwatch-output
      filterRefs:
        - drop-package-operator
        - filter-kube-api-audit
  filters:
    # Drop package operator pod logs
    - name: drop-package-operator
      type: drop
      drop:
      - test:
        - field: .kubernetes.labels."app.kubernetes.io/name"
          matches: ^package-operator$
    # Filter kube-api events in the audit log groups
    - name: filter-kube-api-audit
      type: kubeAPIAudit
      kubeAPIAudit:
        rules:
          # Don't log patch, update, watch and get requests from package-operator as they occur most frequently.
          # It's worth keeping create and delete for audit purposes.
          # In a month, patch called ~40k times more than create.
          - level: None
            userGroups: ["system:serviceaccount:openshift-package-operator:package-operator"]
            verbs: ["patch", "update", "watch", "get"]
