apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudwatch
  namespace: openshift-logging
spec:
  secretStoreRef:
    name: {{ .Values.global.secretStore.aws.secretsManagerSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: cloudwatch
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        aws_access_key_id: {{ printf "'{{ .aws_access_key_id | b64enc }}'" }}
        aws_secret_access_key: {{ printf "'{{ .aws_secret_access_key | b64enc }}'" }}
  data:
    - secretKey: aws_access_key_id # pragma: allowlist secret
      remoteRef:
        key: "logging"
        property: "aws_access_key_id"
    - secretKey: aws_secret_access_key # pragma: allowlist secret
      remoteRef:
        key: "logging"
        property: "aws_secret_access_key"
