apiVersion: "operators.coreos.com/v1alpha1"
kind: Subscription
metadata:
  name: vertical-pod-autoscaler
  namespace: openshift-vertical-pod-autoscaler
spec:
  channel: stable
  installPlanApproval: Automatic
  name: vertical-pod-autoscaler
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  config:
    nodeSelector:
      # For HCP clusters, master nodes are hosted so VPA cannot use master node selectors
      # because of that we need a way to overwrite initial selectors
      node-role.kubernetes.io/worker: ""
