# This CRD is a workaround for making routes created by operator
# For creating routes the operator checks that there is a 'apps.openshift.io/v1' resource
# TODO(ROX-12079): Operator should allow creating routes without running on Openshift
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dummy.apps.openshift.io
spec:
  group: apps.openshift.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
  scope: Namespaced
  names:
    plural: dummy
    singular: dummy
    kind: Dummy
