apiVersion: v1
kind: Secret
metadata:
  name: acs-fleet-manager-rds
  namespace: "$ACSMS_NAMESPACE"
stringData:
  db.host: "${DATABASE_HOST}"
  db.port: "${DATABASE_PORT}"
  db.name: "${DATABASE_NAME}"
  db.user: "${DATABASE_USER}"
  db.password: "${DATABASE_PASSWORD}"
  db.ca_cert: "${DATABASE_TLS_CERT}"
