apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: db
  name: "$DATABASE_HOST"
  namespace: "$ACSMS_NAMESPACE"
spec:
  replicas: 1
  selector:
    matchLabels:
      application: db
  strategy: {}
  template:
    metadata:
      labels:
        application: db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: acs-fleet-manager-rds
                  key: "db.name"
                  optional: false
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: acs-fleet-manager-rds
                  key: "db.password"
                  optional: false
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: acs-fleet-manager-rds
                  key: "db.user"
                  optional: false
            - name: PGDATA
              value: "/tmp/postgresql"
          image: postgres:13
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -h
                - localhost
                - -U
                - "$DATABASE_USER"
                - -d
                - "$DATABASE_NAME"
            failureThreshold: 30
            periodSeconds: 1
            timeoutSeconds: 3
          name: db
          ports:
            - containerPort: 5432
          resources: $DB_RESOURCES
      restartPolicy: Always
