apiVersion: v1
kind: Service
metadata:
  labels:
    application: db
  name: db
  namespace: "$ACSMS_NAMESPACE"
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    application: db
status:
  loadBalancer: {}
