apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-vertical-pod-autoscaler
  namespace: openshift-vertical-pod-autoscaler
spec:
  selector:
    matchExpressions:
      - key: rhacs.redhat.com/tenant
        operator: Exists
  upgradeStrategy: Default
