/*
 * Dinosaur Service Fleet Manager Admin APIs
 *
 * The admin APIs for the fleet manager of Dinosaur service
 *
 * API version: 0.0.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package private

// DinosaurDetailsRoutes struct for DinosaurDetailsRoutes
type DinosaurDetailsRoutes struct {
	Domain string `json:"domain,omitempty"`
	Router string `json:"router,omitempty"`
}
