// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package services

import (
	"github.com/stackrox/acs-fleet-manager/internal/dinosaur/pkg/api/dbapi"
	"github.com/stackrox/acs-fleet-manager/pkg/api"
	"sync"
)

// Ensure, that ClusterPlacementStrategyMock does implement ClusterPlacementStrategy.
// If this is not the case, regenerate this file with moq.
var _ ClusterPlacementStrategy = &ClusterPlacementStrategyMock{}

// ClusterPlacementStrategyMock is a mock implementation of ClusterPlacementStrategy.
//
//	func TestSomethingThatUsesClusterPlacementStrategy(t *testing.T) {
//
//		// make and configure a mocked ClusterPlacementStrategy
//		mockedClusterPlacementStrategy := &ClusterPlacementStrategyMock{
//			AllMatchingClustersForCentralFunc: func(central *dbapi.CentralRequest) ([]*api.Cluster, error) {
//				panic("mock out the AllMatchingClustersForCentral method")
//			},
//			FindClusterFunc: func(central *dbapi.CentralRequest) (*api.Cluster, error) {
//				panic("mock out the FindCluster method")
//			},
//		}
//
//		// use mockedClusterPlacementStrategy in code that requires ClusterPlacementStrategy
//		// and then make assertions.
//
//	}
type ClusterPlacementStrategyMock struct {
	// AllMatchingClustersForCentralFunc mocks the AllMatchingClustersForCentral method.
	AllMatchingClustersForCentralFunc func(central *dbapi.CentralRequest) ([]*api.Cluster, error)

	// FindClusterFunc mocks the FindCluster method.
	FindClusterFunc func(central *dbapi.CentralRequest) (*api.Cluster, error)

	// calls tracks calls to the methods.
	calls struct {
		// AllMatchingClustersForCentral holds details about calls to the AllMatchingClustersForCentral method.
		AllMatchingClustersForCentral []struct {
			// Central is the central argument value.
			Central *dbapi.CentralRequest
		}
		// FindCluster holds details about calls to the FindCluster method.
		FindCluster []struct {
			// Central is the central argument value.
			Central *dbapi.CentralRequest
		}
	}
	lockAllMatchingClustersForCentral sync.RWMutex
	lockFindCluster                   sync.RWMutex
}

// AllMatchingClustersForCentral calls AllMatchingClustersForCentralFunc.
func (mock *ClusterPlacementStrategyMock) AllMatchingClustersForCentral(central *dbapi.CentralRequest) ([]*api.Cluster, error) {
	if mock.AllMatchingClustersForCentralFunc == nil {
		panic("ClusterPlacementStrategyMock.AllMatchingClustersForCentralFunc: method is nil but ClusterPlacementStrategy.AllMatchingClustersForCentral was just called")
	}
	callInfo := struct {
		Central *dbapi.CentralRequest
	}{
		Central: central,
	}
	mock.lockAllMatchingClustersForCentral.Lock()
	mock.calls.AllMatchingClustersForCentral = append(mock.calls.AllMatchingClustersForCentral, callInfo)
	mock.lockAllMatchingClustersForCentral.Unlock()
	return mock.AllMatchingClustersForCentralFunc(central)
}

// AllMatchingClustersForCentralCalls gets all the calls that were made to AllMatchingClustersForCentral.
// Check the length with:
//
//	len(mockedClusterPlacementStrategy.AllMatchingClustersForCentralCalls())
func (mock *ClusterPlacementStrategyMock) AllMatchingClustersForCentralCalls() []struct {
	Central *dbapi.CentralRequest
} {
	var calls []struct {
		Central *dbapi.CentralRequest
	}
	mock.lockAllMatchingClustersForCentral.RLock()
	calls = mock.calls.AllMatchingClustersForCentral
	mock.lockAllMatchingClustersForCentral.RUnlock()
	return calls
}

// FindCluster calls FindClusterFunc.
func (mock *ClusterPlacementStrategyMock) FindCluster(central *dbapi.CentralRequest) (*api.Cluster, error) {
	if mock.FindClusterFunc == nil {
		panic("ClusterPlacementStrategyMock.FindClusterFunc: method is nil but ClusterPlacementStrategy.FindCluster was just called")
	}
	callInfo := struct {
		Central *dbapi.CentralRequest
	}{
		Central: central,
	}
	mock.lockFindCluster.Lock()
	mock.calls.FindCluster = append(mock.calls.FindCluster, callInfo)
	mock.lockFindCluster.Unlock()
	return mock.FindClusterFunc(central)
}

// FindClusterCalls gets all the calls that were made to FindCluster.
// Check the length with:
//
//	len(mockedClusterPlacementStrategy.FindClusterCalls())
func (mock *ClusterPlacementStrategyMock) FindClusterCalls() []struct {
	Central *dbapi.CentralRequest
} {
	var calls []struct {
		Central *dbapi.CentralRequest
	}
	mock.lockFindCluster.RLock()
	calls = mock.calls.FindCluster
	mock.lockFindCluster.RUnlock()
	return calls
}
