// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package services

import (
	"context"
	"github.com/stackrox/acs-fleet-manager/internal/dinosaur/pkg/api/dbapi"
	"github.com/stackrox/acs-fleet-manager/internal/dinosaur/pkg/dinosaurs/types"
	serviceError "github.com/stackrox/acs-fleet-manager/pkg/errors"
	"sync"
)

// Ensure, that QuotaServiceMock does implement QuotaService.
// If this is not the case, regenerate this file with moq.
var _ QuotaService = &QuotaServiceMock{}

// QuotaServiceMock is a mock implementation of QuotaService.
//
//	func TestSomethingThatUsesQuotaService(t *testing.T) {
//
//		// make and configure a mocked QuotaService
//		mockedQuotaService := &QuotaServiceMock{
//			DeleteQuotaFunc: func(subscriptionID string) *serviceError.ServiceError {
//				panic("mock out the DeleteQuota method")
//			},
//			IsQuotaActiveFunc: func(dinosaur *dbapi.CentralRequest, instanceType types.DinosaurInstanceType) (bool, *serviceError.ServiceError) {
//				panic("mock out the IsQuotaActive method")
//			},
//			ReserveQuotaFunc: func(ctx context.Context, dinosaur *dbapi.CentralRequest, instanceType types.DinosaurInstanceType) (string, *serviceError.ServiceError) {
//				panic("mock out the ReserveQuota method")
//			},
//		}
//
//		// use mockedQuotaService in code that requires QuotaService
//		// and then make assertions.
//
//	}
type QuotaServiceMock struct {
	// DeleteQuotaFunc mocks the DeleteQuota method.
	DeleteQuotaFunc func(subscriptionID string) *serviceError.ServiceError

	// IsQuotaActiveFunc mocks the IsQuotaActive method.
	IsQuotaActiveFunc func(dinosaur *dbapi.CentralRequest, instanceType types.DinosaurInstanceType) (bool, *serviceError.ServiceError)

	// ReserveQuotaFunc mocks the ReserveQuota method.
	ReserveQuotaFunc func(ctx context.Context, dinosaur *dbapi.CentralRequest, instanceType types.DinosaurInstanceType) (string, *serviceError.ServiceError)

	// calls tracks calls to the methods.
	calls struct {
		// DeleteQuota holds details about calls to the DeleteQuota method.
		DeleteQuota []struct {
			// SubscriptionID is the subscriptionID argument value.
			SubscriptionID string
		}
		// IsQuotaActive holds details about calls to the IsQuotaActive method.
		IsQuotaActive []struct {
			// Dinosaur is the dinosaur argument value.
			Dinosaur *dbapi.CentralRequest
			// InstanceType is the instanceType argument value.
			InstanceType types.DinosaurInstanceType
		}
		// ReserveQuota holds details about calls to the ReserveQuota method.
		ReserveQuota []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Dinosaur is the dinosaur argument value.
			Dinosaur *dbapi.CentralRequest
			// InstanceType is the instanceType argument value.
			InstanceType types.DinosaurInstanceType
		}
	}
	lockDeleteQuota   sync.RWMutex
	lockIsQuotaActive sync.RWMutex
	lockReserveQuota  sync.RWMutex
}

// DeleteQuota calls DeleteQuotaFunc.
func (mock *QuotaServiceMock) DeleteQuota(subscriptionID string) *serviceError.ServiceError {
	if mock.DeleteQuotaFunc == nil {
		panic("QuotaServiceMock.DeleteQuotaFunc: method is nil but QuotaService.DeleteQuota was just called")
	}
	callInfo := struct {
		SubscriptionID string
	}{
		SubscriptionID: subscriptionID,
	}
	mock.lockDeleteQuota.Lock()
	mock.calls.DeleteQuota = append(mock.calls.DeleteQuota, callInfo)
	mock.lockDeleteQuota.Unlock()
	return mock.DeleteQuotaFunc(subscriptionID)
}

// DeleteQuotaCalls gets all the calls that were made to DeleteQuota.
// Check the length with:
//
//	len(mockedQuotaService.DeleteQuotaCalls())
func (mock *QuotaServiceMock) DeleteQuotaCalls() []struct {
	SubscriptionID string
} {
	var calls []struct {
		SubscriptionID string
	}
	mock.lockDeleteQuota.RLock()
	calls = mock.calls.DeleteQuota
	mock.lockDeleteQuota.RUnlock()
	return calls
}

// IsQuotaActive calls IsQuotaActiveFunc.
func (mock *QuotaServiceMock) IsQuotaActive(dinosaur *dbapi.CentralRequest, instanceType types.DinosaurInstanceType) (bool, *serviceError.ServiceError) {
	if mock.IsQuotaActiveFunc == nil {
		panic("QuotaServiceMock.IsQuotaActiveFunc: method is nil but QuotaService.IsQuotaActive was just called")
	}
	callInfo := struct {
		Dinosaur     *dbapi.CentralRequest
		InstanceType types.DinosaurInstanceType
	}{
		Dinosaur:     dinosaur,
		InstanceType: instanceType,
	}
	mock.lockIsQuotaActive.Lock()
	mock.calls.IsQuotaActive = append(mock.calls.IsQuotaActive, callInfo)
	mock.lockIsQuotaActive.Unlock()
	return mock.IsQuotaActiveFunc(dinosaur, instanceType)
}

// IsQuotaActiveCalls gets all the calls that were made to IsQuotaActive.
// Check the length with:
//
//	len(mockedQuotaService.IsQuotaActiveCalls())
func (mock *QuotaServiceMock) IsQuotaActiveCalls() []struct {
	Dinosaur     *dbapi.CentralRequest
	InstanceType types.DinosaurInstanceType
} {
	var calls []struct {
		Dinosaur     *dbapi.CentralRequest
		InstanceType types.DinosaurInstanceType
	}
	mock.lockIsQuotaActive.RLock()
	calls = mock.calls.IsQuotaActive
	mock.lockIsQuotaActive.RUnlock()
	return calls
}

// ReserveQuota calls ReserveQuotaFunc.
func (mock *QuotaServiceMock) ReserveQuota(ctx context.Context, dinosaur *dbapi.CentralRequest, instanceType types.DinosaurInstanceType) (string, *serviceError.ServiceError) {
	if mock.ReserveQuotaFunc == nil {
		panic("QuotaServiceMock.ReserveQuotaFunc: method is nil but QuotaService.ReserveQuota was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		Dinosaur     *dbapi.CentralRequest
		InstanceType types.DinosaurInstanceType
	}{
		Ctx:          ctx,
		Dinosaur:     dinosaur,
		InstanceType: instanceType,
	}
	mock.lockReserveQuota.Lock()
	mock.calls.ReserveQuota = append(mock.calls.ReserveQuota, callInfo)
	mock.lockReserveQuota.Unlock()
	return mock.ReserveQuotaFunc(ctx, dinosaur, instanceType)
}

// ReserveQuotaCalls gets all the calls that were made to ReserveQuota.
// Check the length with:
//
//	len(mockedQuotaService.ReserveQuotaCalls())
func (mock *QuotaServiceMock) ReserveQuotaCalls() []struct {
	Ctx          context.Context
	Dinosaur     *dbapi.CentralRequest
	InstanceType types.DinosaurInstanceType
} {
	var calls []struct {
		Ctx          context.Context
		Dinosaur     *dbapi.CentralRequest
		InstanceType types.DinosaurInstanceType
	}
	mock.lockReserveQuota.RLock()
	calls = mock.calls.ReserveQuota
	mock.lockReserveQuota.RUnlock()
	return calls
}
