---
# A list of additional SSO issuers that should be verified for issued tokens.
# This will include the staging environment of sso.redhat.com to enable UI development
# to be unblocked.
# Endpoints must be given in the format https://<endpoint>/auth/realms/<your-realm> without trailing slash.
- https://sso.stage.redhat.com/auth/realms/redhat-external
