---
#- A list of clusters for fleet manager
#- The `cluster_id` field can not be empty
#- All clusters in fleet manager DB already but are missing in the list will be marked as
#  'deprovisioning' and will later be deleted.
#- This list is ordered, any new cluster should be appended at the end.
clusters:
 - name: default/api-juan-fm-dev-94xt-s1-devshift-org:6443/admin
   cluster_id: 1sh266ouf8lipuid2c0rna877eou6ecc
   cloud_provider: aws
   region: us-west-2
   schedulable: true
   status: ready
   dinosaur_instance_limit: 10
   provider_type: standalone
   supported_instance_type: "eval,standard"
   cluster_dns: juan-fm-dev.94xt.s1.devshift.org
