---
#- A list of clusters for fleet manager
#- The `cluster_id` field can not be empty
#- All clusters in fleet manager DB already but are missing in the list will be marked as
#  'deprovisioning' and will later be deleted.
#- This list is ordered, any new cluster should be appended at the end.
clusters:
 - name: default/api-evan-acsms-fm-d-0a51-s2-devshift-org:6443/admin
   cluster_id: 1sdu4lati28ifrnk73d3o4qa720rb5ek
   cloud_provider: gcp
   region: us-east1
   schedulable: true
   status: ready
   dinosaur_instance_limit: 10
   provider_type: standalone
   supported_instance_type: "eval,standard"
   cluster_dns: evan-acsms-fm-d.0a51.s2.devshift.org
