---
#- A list of clusters for fleet manager
#- The `cluster_id` field can not be empty
#- All clusters in fleet manager DB already but are missing in the list will be marked as
#  'deprovisioning' and will later be deleted.
#- This list is ordered, any new cluster should be appended at the end.
clusters:
 - name: default/api-jmalsam-test-rfse-p1-openshiftapps-com:6443/jmalsam
   cluster_id: 1sdu4lati28ifrnk73d3o4qa720rb5ek
   cloud_provider: standalone
   region: standalone
   schedulable: true
   status: ready
   central_instance_limit: 10
   provider_type: standalone
   supported_instance_type: "eval,standard"
   cluster_dns: jmalsam-test.rfse.p1.openshiftapps.com
   multi_az: true
