image: "quay.io/rhacs-eng/blackbox-monitoring-probe-service:main"
namespace: "rhacs-probe"
fleetManagerEndpoint: ""
clusterName: ""
environment: ""
dataPlaneRegion: "us-east-1"
# Must be either 'RHSSO' or 'OCM'.
authType: "RHSSO"
ocm:
  # The username of the Red Hat SSO account.
  username: ""
  # The refresh token obtained from `ocm token --refresh`.
  token: ""
redHatSSO:
  clientId: ""
  clientSecret: ""
  endpoint: "https://sso.redhat.com"
  realm: "redhat-external"
resources:
  limits:
    cpu: "100m"
    memory: "128Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"
