image: "quay.io/rhacs-eng/blackbox-monitoring-probe-service:main"
namespace: "rhacs-probe"
fleetManagerEndpoint: ""
# Must be either 'RHSSO' or 'OCM'.
authType: "RHSSO"
ocm:
  # The username of the Red Hat SSO account.
  username: ""
  # The refresh token obtained from `ocm token --refresh`.
  token: ""
redHatSSO:
  clientId: ""
  clientSecret: ""
  endpoint: "https://sso.redhat.com"
  realm: "redhat-external"
