apiVersion: v1
kind: Secret
metadata:
  name: fleetshard-sync
  namespace: "$ACSCS_NAMESPACE"
stringData:
  kubeconfig: |
    ${KUBE_CONFIG}
  rhsso-service-account-client-id: "${RHSSO_SERVICE_ACCOUNT_CLIENT_ID}"
  rhsso-service-account-client-secret: "${RHSSO_SERVICE_ACCOUNT_CLIENT_SECRET}"
  aws-role-arn: "${AWS_ROLE_ARN}"
  aws-access-key-id: "${AWS_ACCESS_KEY_ID}"
  aws-secret-access-key: "${AWS_SECRET_ACCESS_KEY}"
