apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: fleetshard-sync
  name: fleetshard-sync
  namespace: "$ACSMS_NAMESPACE"
spec:
  replicas: 1
  selector:
    matchLabels:
      application: fleetshard-sync
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        application: fleetshard-sync
    spec:
      containers:
        - command:
            - /usr/local/bin/fleetshard-sync
          env:
            - name: KUBECONFIG
              value: "/secrets/kubeconfig"
            - name: CLUSTER_ID
              value: "1234567890abcdef1234567890abcdef" # pragma: allowlist secret
            - name: FLEET_MANAGER_ENDPOINT
              value: http://fleet-manager:8000
            - name: AUTH_TYPE
              value: "$AUTH_TYPE"
            - name: STATIC_TOKEN
              valueFrom:
                secretKeyRef:
                  name: fleet-manager
                  key: "fleet-static-token"
                  optional: false
            - name: OCM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: fleet-manager
                  key: "ocm-service.token"
                  optional: false
            - name: RUNTIME_POLL_PERIOD
              value: 10s

          image: "${FLEET_MANAGER_IMAGE}"
          imagePullPolicy: IfNotPresent
          name: fleetshard-sync
          resources: $FLEETSHARD_SYNC_RESOURCES
          volumeMounts:
            - mountPath: /secrets
              name: secrets
            - mountPath: /config
              name: config
      restartPolicy: Always
      volumes:
        - name: secrets
          secret:
            secretName: fleet-manager # pragma: allowlist secret
            optional: false
        - name: config
          configMap:
            name: config
