apiVersion: v1
kind: Secret
metadata:
  name: fleetshard-sync
  namespace: "$ACSMS_NAMESPACE"
stringData:
  kubeconfig: |
    ${KUBE_CONFIG}
  rhsso-service-account-client-id: "${RHSSO_SERVICE_ACCOUNT_CLIENT_ID}"
  rhsso-service-account-client-secret: "${RHSSO_SERVICE_ACCOUNT_CLIENT_SECRET}"
  rds-access-key-id: "${MANAGED_DB_ACCESS_KEY_ID}"
  rds-secret-access-key: "${MANAGED_DB_SECRET_ACCESS_KEY}"
  rds-sesion-token: "${MANAGED_DB_SESSION_TOKEN}"
