{
 "title": "ACS Fleet Manager SLOs",
 "time": { "from": "now-28d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "acs-fleet-manager-integration,acs-fleet-manager-stage,acs-fleet-manager-production"
   }
  ]
 },
 "panels": [
  {
   "title": "API Availability > 99%",
   "type": "gauge",
   "description": "The availability SLI is calculated as the product of the pod ready SLI and http error rate SLI. For the service to be available, at least one pod must be ready and the http error rate over the last 10 minutes must be below 35%.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(acs_fleet_manager:sli:availability[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Latency p90 < 0.1s",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(api_inbound_request_duration_bucket{job=\"fleet-manager-metrics\",namespace=\"$namespace\",le=\"0.1\"}[$__range]))/sum(rate(api_inbound_request_duration_count{job=\"fleet-manager-metrics\",namespace=\"$namespace\"}[$__range]))"
    }
   ]
  },
  {
   "title": "API Latency p99 < 1s",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(api_inbound_request_duration_bucket{job=\"fleet-manager-metrics\",namespace=\"$namespace\",le=\"1\"}[$__range]))/sum(rate(api_inbound_request_duration_count{job=\"fleet-manager-metrics\",namespace=\"$namespace\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Correctness (Create) > 95%",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(acs_fleet_manager_central_operations_success_count{job=\"fleet-manager-metrics\",namespace=\"$namespace\"}[$__range]))/sum(rate(acs_fleet_manager_central_operations_total_count{job=\"fleet-manager-metrics\",namespace=\"$namespace\"}[$__range]))",
     "legendFormat": "Create Operation"
    }
   ]
  },
  {
   "title": "Correctness (Delete) > 95%",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(acs_fleet_manager_central_operations_success_count{job=\"fleet-manager-metrics\",namespace=\"$namespace\", operation=\"delete\"}[$__range]))/sum(rate(acs_fleet_manager_central_operations_total_count{job=\"fleet-manager-metrics\",namespace=\"$namespace\", operation=\"delete\"}[$__range]))",
     "legendFormat": "Create Operation"
    }
   ]
  },
  {
   "title": "Creation latency p90 < 60m",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(acs_fleet_manager_worker_central_duration_bucket{job=\"fleet-manager-metrics\",namespace=\"$namespace\",jobType=\"central_create\", le=\"3600\"}[$__range])+1) / sum(rate(acs_fleet_manager_worker_central_duration_count{job=\"fleet-manager-metrics\",namespace=\"$namespace\",jobType=\"central_create\"}[$__range])+1)",
     "legendFormat": "Create Operation"
    }
   ]
  },
  {
   "title": "Error budget exhaustion",
   "type": "gauge",
   "description": "An error budget is the maximum amount errors that a technical system can fail without contractual consequences. The Error budget exhaustion shows how much allowable errors the service has used. For example, we have API Availability 99% target value. Suppose that actual value is 99.7%. That means that error budget is 1% and error budget exhaustion is 30%.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - avg_over_time(acs_fleet_manager:sli:availability[$__range])) / (1 - acs_fleet_manager:slo:availability)",
     "legendFormat": "API Availability > 99%"
    },
    {
     "expr": "(1-(sum(rate(api_inbound_request_duration_bucket{job=\"fleet-manager-metrics\",namespace=\"$namespace\",le=\"0.1\"}[$__range]))/sum(rate(api_inbound_request_duration_count{job=\"fleet-manager-metrics\",namespace=\"$namespace\"}[$__range]))))/(1-0.9)",
     "legendFormat": "API Latency p90 < 0.1s"
    },
    {
     "expr": "(1-sum(rate(api_inbound_request_duration_bucket{job=\"fleet-manager-metrics\",namespace=\"$namespace\",le=\"1\"}[$__range]))/sum(rate(api_inbound_request_duration_count{job=\"fleet-manager-metrics\",namespace=\"$namespace\"}[$__range])))/(1-0.99)",
     "legendFormat": "API Latency p99"
    },
    {
     "expr": "(1-sum(rate(acs_fleet_manager_central_operations_success_count{job=\"fleet-manager-metrics\",namespace=\"$namespace\"}[$__range]))/sum(rate(acs_fleet_manager_central_operations_total_count{job=\"fleet-manager-metrics\",namespace=\"$namespace\"}[$__range])))/(1-0.95)",
     "legendFormat": "Correctness (Create) > 95%"
    },
    {
     "expr": "(1-sum(rate(acs_fleet_manager_central_operations_success_count{job=\"fleet-manager-metrics\",namespace=\"$namespace\", operation=\"delete\"}[$__range]))/sum(rate(acs_fleet_manager_central_operations_total_count{job=\"fleet-manager-metrics\",namespace=\"$namespace\", operation=\"delete\"}[$__range])))/(1-0.95)",
     "legendFormat": "Correctness (Delete) > 95%"
    },
    {
     "expr": "(1-sum(rate(acs_fleet_manager_worker_central_duration_bucket{job=\"fleet-manager-metrics\",namespace=\"$namespace\",jobType=\"central_create\", le=\"3600\"}[$__range])+1) / sum(rate(acs_fleet_manager_worker_central_duration_count{job=\"fleet-manager-metrics\",namespace=\"$namespace\",jobType=\"central_create\"}[$__range])+1))/(1-0.9)",
     "legendFormat": "Creation latency p90 < 60m"
    }
   ]
  },
  {
   "title": "API Availability",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "acs_fleet_manager:sli:availability",
     "legendFormat": "acs-fleet-manager"
    }
   ]
  },
  {
   "title": "API Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(api_inbound_request_duration_bucket{job=\"fleet-manager-metrics\",namespace=\"$namespace\"}[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(api_inbound_request_duration_bucket{job=\"fleet-manager-metrics\",namespace=\"$namespace\"}[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(api_inbound_request_duration_bucket{job=\"fleet-manager-metrics\",namespace=\"$namespace\"}[5m])) by (le))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Lifecycle Correctness",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(acs_fleet_manager_central_operations_success_count{job=\"fleet-manager-metrics\",namespace=\"$namespace\"}[1w]))/sum(rate(acs_fleet_manager_central_operations_total_count{job=\"fleet-manager-metrics\",namespace=\"$namespace\"}[1w]))",
     "legendFormat": "Create Operation"
    },
    {
     "expr": "sum(rate(acs_fleet_manager_central_operations_success_count{job=\"fleet-manager-metrics\",namespace=\"$namespace\",operation=\"delete\"}[1w]))/sum(rate(acs_fleet_manager_central_operations_total_count{job=\"fleet-manager-metrics\",namespace=\"$namespace\",operation=\"delete\"}[1w]))",
     "legendFormat": "Delete Operation"
    }
   ]
  },
  {
   "title": "Creation Latency histogram (in seconds)",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(acs_fleet_manager_worker_central_duration_bucket{namespace=\"$namespace\",jobType=\"central_create\"}[$__range])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}