{
 "title": "ACS Fleet Manager",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "acs-fleet-manager-integration,acs-fleet-manager-stage,acs-fleet-manager-production"
   }
  ]
 },
 "panels": [
  {
   "title": "Envoy request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_total{namespace=\"$namespace\",service=\"fleet-manager-envoy-metrics\",envoy_cluster_name=\"backend\"}[$__rate_interval]))",
     "legendFormat": "Inbound"
    }
   ]
  },
  {
   "title": "Requests rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(api_inbound_request_count{namespace=\"$namespace\",service=\"fleet-manager-metrics\"}[$__rate_interval]))",
     "legendFormat": "Inbound"
    },
    {
     "expr": "sum(rate(api_outbound_request_count{namespace=\"$namespace\",service=\"fleet-manager-metrics\"}[$__rate_interval]))",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Response codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(api_inbound_request_count{namespace=\"$namespace\",service=\"fleet-manager-metrics\"}[$__rate_interval])) by (code)",
     "legendFormat": "Inbound {{code}}"
    },
    {
     "expr": "sum(rate(api_outbound_request_count{namespace=\"$namespace\",service=\"fleet-manager-metrics\"}[$__rate_interval])) by (code)",
     "legendFormat": "Outbound {{code}}"
    }
   ]
  },
  {
   "title": "Heap usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{namespace=\"$namespace\",service=\"fleet-manager-metrics\"} +\ngo_memstats_heap_idle_bytes{namespace=\"$namespace\",service=\"fleet-manager-metrics\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{namespace=\"$namespace\",service=\"fleet-manager-metrics\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{namespace=\"$namespace\",service=\"fleet-manager-metrics\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}