apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: acscs-manifests.stackrox.github.com
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/stackrox/acscs-manifests.git
  username: not-used
  password: "$GITHUB_TOKEN" # pragma: allowlist secret
