# Allows the ArgoCD application controller to manage additional resources
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: custom-acscs-openshift-gitops
rules:
  # Allow managing stackrox centrals
  - apiGroups: [ "platform.stackrox.io" ]
    resources: [ "centrals" ]
    verbs: [ "*" ]
  # Allow managing CRDs
  - apiGroups: [ "apiextensions.k8s.io" ]
    resources: [ "customresourcedefinitions" ]
    verbs: [ "*" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: custom-acscs-openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: custom-acscs-openshift-gitops
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
