kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: acscs-cluster
subjects:
  - kind: ServiceAccount
    name: default
    namespace: "$ACSCS_NAMESPACE"
roleRef:
  kind: ClusterRole
  name: acscs
  apiGroup: rbac.authorization.k8s.io
