# permissions for end users to edit terraforms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: terraform-editor-role
rules:
- apiGroups:
  - dataplane.acs.rhcloud.com
  resources:
  - terraforms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dataplane.acs.rhcloud.com
  resources:
  - terraforms/status
  verbs:
  - get
