---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: PostgreSQL database service for use with the Managed Services API
    iconClass: icon-postgresql
    openshift.io/display-name: Dinosaur Service Fleet Manager PostgreSQL Database
    tags: database,postgresql
  name: fleet-manager-db
parameters:

  - name: POSTGRESQL_IMAGESTREAM_NAMESPACE
    description: The OpenShift Namespace where the ImageStream resides.
    displayName: Namespace
    value: openshift

  - name: DATABASE_SERVICE_NAME
    description: The name of the OpenShift Service exposed for the database.
    displayName: Dinosaur Service Fleet Manager Database
    required: true
    value: fleet-manager-db

  - name: DATABASE_USER
    description: Username for PostgreSQL user that will be used for accessing the database.
    displayName: PostgreSQLUsername
    required: true
    value: ocm

  - name: DATABASE_PASSWORD
    description: Password for the PostgreSQL connection user.
    displayName: PostgreSQL Password
    required: true
    value: TheBlurstOfTimes

  - name: DATABASE_NAME
    description: Name of the PostgreSQL database accessed.
    displayName: PostgreSQL Database Name
    required: true
    value: fleet-manager

  - name: DATABASE_VOLUME_CAPACITY
    description: Volume space available for data, e.g. 512Mi, 2Gi.
    displayName: Volume Capacity
    required: true
    value: 512Mi

  - name: POSTGRESQL_VERSION
    description: Version of PostgreSQL image to be used (10 or latest).
    displayName: Version of PostgreSQL Image
    required: true
    value: "13"

objects:

  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        template.openshift.io/expose-uri: postgres://{.spec.clusterIP}:{.spec.ports[?(.name==\postgresql\)].port}
      name: ${DATABASE_SERVICE_NAME}
    spec:
      ports:
        - name: postgresql
          port: 5432
          targetPort: 5432
      selector:
        application: ${DATABASE_SERVICE_NAME}
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: ${DATABASE_SERVICE_NAME}
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: ${DATABASE_VOLUME_CAPACITY}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        template.alpha.openshift.io/wait-for-ready: "true"
      name: ${DATABASE_SERVICE_NAME}
      labels:
        application: ${DATABASE_SERVICE_NAME}
    spec:
      replicas: 1
      selector:
        matchLabels:
          application: ${DATABASE_SERVICE_NAME}
      strategy: {}
      template:
        metadata:
          labels:
            application: ${DATABASE_SERVICE_NAME}
        spec:
          containers:
            - capabilities: {}
              env:
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      key: database-user
                      name: ${DATABASE_SERVICE_NAME}
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-password
                      name: ${DATABASE_SERVICE_NAME}
                - name: POSTGRES_DB
                  valueFrom:
                    secretKeyRef:
                      key: database-name
                      name: ${DATABASE_SERVICE_NAME}
              image: postgres:${POSTGRESQL_VERSION}
              imagePullPolicy: IfNotPresent
              name: postgresql
              ports:
                - containerPort: 5432
                  protocol: TCP
              readinessProbe:
                exec:
                  command:
                    - pg_isready
                    - -h
                    - localhost
                    - -U
                    - "${DATABASE_USER}"
                    - -d
                    - "${DATABASE_NAME}"
                failureThreshold: 30
                periodSeconds: 1
                timeoutSeconds: 3
              securityContext:
                capabilities: {}
                privileged: false
              terminationMessagePath: /dev/termination-log
              volumeMounts:
                - mountPath: /var/lib/pgsql/data
                  name: ${DATABASE_SERVICE_NAME}-data
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          volumes:
            - name: ${DATABASE_SERVICE_NAME}-data
              persistentVolumeClaim:
                claimName: ${DATABASE_SERVICE_NAME}

  - apiVersion: v1
    kind: Secret
    metadata:
      annotations:
        template.openshift.io/expose-database_name: "{.data['database-name']}"
        template.openshift.io/expose-password: "{.data['database-password']}"
        template.openshift.io/expose-username: "{.data['database-user']}"
      name: ${DATABASE_SERVICE_NAME}
    stringData:
      database-name: ${DATABASE_NAME}
      database-password: ${DATABASE_PASSWORD}
      database-user: ${DATABASE_USER}
