---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: fleet-manager-probe
  annotations:
    openshift.io/display-name: Fleet Manager Probe
    description: ACS Services Fleet Manager Probe
    tags: golang
    iconClass: icon-shadowman
labels:
  template: fleet-manager-probe
parameters:
  - name: IMAGE_REGISTRY
    displayName: Image Registry
    required: true
  - name: IMAGE_REPOSITORY
    displayName: Image Repository
    required: true
  - name: IMAGE_TAG
    displayName: Image tag
    value: latest
  - name: FLEET_MANAGER_ENDPOINT
    displayName: Fleet Manager Endpoint
    value: http://fleet-manager.rhacs:8000
  - name: CENTRAL_SPECS
    display: Central Specifications
    value: '[{ "cloudProvider": "standalone", "region": "standalone" }]'
  - name: CPU_REQUESTS
    displayName: CPU Requests
    value: 100m
  - name: CPU_LIMITS
    displayName: CPU Limits
    value: 100m
  - name: MEMORY_REQUESTS
    displayName: Memory Requests
    value: 128Mi
  - name: MEMORY_LIMITS
    displayName: Memory Limits
    value: 128Mi
objects:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: probe
      labels:
        app: probe
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: probe
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            app: probe
        spec:
          containers:
            - name: probe
              image: "${IMAGE_REGISTRY}/${IMAGE_REPOSITORY}:${IMAGE_TAG}"
              imagePullPolicy: IfNotPresent
              env:
                - name: FLEET_MANAGER_ENDPOINT
                  value: ${FLEET_MANAGER_ENDPOINT}
                - name: AUTH_TYPE
                  value: OCM
                - name: OCM_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: probe-credentials
                      key: OCM_USERNAME
                - name: OCM_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: probe-credentials
                      key: OCM_TOKEN
                - name: CENTRAL_SPECS
                  value: ${CENTRAL_SPECS}
              ports:
                - name: monitoring
                  containerPort: 7070
              resources:
                requests:
                  cpu: ${CPU_REQUESTS}
                  memory: ${MEMORY_REQUESTS}
                limits:
                  cpu: ${CPU_LIMITS}
                  memory: ${MEMORY_LIMITS}
          terminationGracePeriodSeconds: 300
