---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: fleet-manager-secrets
  annotations:
    description: "ACSCS Fleet Manager Secrets"
parameters:

- name: DATABASE_TLS_CERT
  description: TLS cert used by the database to encrypt traffic (if ssl mode is on)

- name: DATABASE_HOST
  description: Hostname for the database server.

- name: DATABASE_PORT
  description: Port of the database server.
  value: "5432"

- name: DATABASE_NAME
  description: Name for the database in the server.
  value: fleet-manager

- name: DATABASE_USER
  description: User for the database server.
  value: ocm

- name: DATABASE_PASSWORD
  description: Password for the database user.
  value: TheBlurstOfTimes

- name: CENTRAL_IDP_CLIENT_SECRET
  description: Client secret to pass to Central's auth config to set up its IdP integration.

- name: OCM_SERVICE_CLIENT_ID
  description: Client id used to interact with other UHC services

- name: OCM_SERVICE_CLIENT_SECRET
  description: Client secret used to interact with other UHC services

- name: OCM_SERVICE_TOKEN
  description: Offline token used to interact with other UHC services

- name: OCM_ADDON_SERVICE_CLIENT_ID
  description: Client id used to interact with OCM Addon Service

- name: OCM_ADDON_SERVICE_CLIENT_SECRET
  description: Client secret used to interact with OCM Addon Service

- name: OCM_ADDON_SERVICE_TOKEN
  description: Offline token used to interact with OCM Addon Service

- name: SENTRY_KEY
  description: Private key used in Sentry DSN

- name: AWS_ACCESS_KEY
  description: AWS access key used to create CCS clusters

- name: AWS_ACCOUNT_ID
  description: AWS account id used to create CCS clusters

- name: AWS_SECRET_ACCESS_KEY
  description: AWS secret access key used to create CCS clusters

- name: ROUTE53_ACCESS_KEY
  description: AWS route 53 access key for creating CNAME records

- name: ROUTE53_SECRET_ACCESS_KEY
  description: AWS route 53 secret access key for creating CNAME records

- name: SSO_CLIENT_ID
  description: Client id used to interact with mas sso

- name: SSO_CLIENT_SECRET
  description: Client secret used to interact with mas sso

- name: CENTRAL_TLS_CERT
  description: Base64 encoded Central TLS certificate

- name: CENTRAL_TLS_KEY
  description: Base64 encoded Central TLS certificate private key

objects:

- apiVersion: v1
  kind: Secret
  metadata:
    name: acs-fleet-manager-rds
  stringData:
    db.host: ${DATABASE_HOST}
    db.port: ${DATABASE_PORT}
    db.name: ${DATABASE_NAME}
    db.user: ${DATABASE_USER}
    db.password: ${DATABASE_PASSWORD}
    db.ca_cert: ${DATABASE_TLS_CERT}

- apiVersion: v1
  kind: Secret
  metadata:
    name: fleet-manager-credentials
  stringData:
    central.idp-client-secret: "${CENTRAL_IDP_CLIENT_SECRET}"
    ocm-service.clientId: ${OCM_SERVICE_CLIENT_ID}
    ocm-service.clientSecret: ${OCM_SERVICE_CLIENT_SECRET}
    ocm-service.token: ${OCM_SERVICE_TOKEN}
    ocm-addon-service.clientId: ${OCM_ADDON_SERVICE_CLIENT_ID}
    ocm-addon-service.clientSecret: ${OCM_ADDON_SERVICE_CLIENT_SECRET}
    ocm-addon-service.token: ${OCM_ADDON_SERVICE_TOKEN}
    sentry.key: ${SENTRY_KEY}
    aws.accesskey: ${AWS_ACCESS_KEY}
    aws.accountid: ${AWS_ACCOUNT_ID}
    aws.secretaccesskey: ${AWS_SECRET_ACCESS_KEY}
    redhatsso-service.clientId: ${SSO_CLIENT_ID}
    redhatsso-service.clientSecret: ${SSO_CLIENT_SECRET}
    aws.route53accesskey: ${ROUTE53_ACCESS_KEY}
    aws.route53secretaccesskey: ${ROUTE53_SECRET_ACCESS_KEY}

- apiVersion: v1
  kind: Secret
  metadata:
    name: fleet-manager-dataplane-certificate
  data:
    tls.crt: ${CENTRAL_TLS_CERT}
    tls.key: ${CENTRAL_TLS_KEY}
