#!/usr/bin/env bash
set -eo pipefail

## This script can apply Kubernetes manifests provided as parameters -- either individual files or directories with manifests.

GITROOT="$(git rev-parse --show-toplevel)"
export GITROOT
# shellcheck source=/dev/null
source "${GITROOT}/dev/env/scripts/lib.sh"

apply_res() {
    local path="$1"
    local short_path
    short_path=${path/#${GITROOT}/}
    res=$(envsubst <"$path")
    log "Applying resource from '${short_path}'"
    echo "$res" | $KUBECTL apply --server-side -f -
}

for path in "$@"; do

    if [[ -d "$path" ]]; then
        mapfile -t files < <(find "$path" -name "*.yaml" -type f | sort -n)
        wait "$!" || { log "Failed to discover manifests in '${path}'"; exit 1; }
        for f in "${files[@]}"; do
            apply_res "$f"
        done
    else
        apply_res "$path"
    fi

done
