#!/usr/bin/env bash

## This script assembles ImagePullSecrets for quay.io and registry.redhat.io as Kubernetes manifests ready for applying them to a cluster.

GITROOT="$(git rev-parse --show-toplevel)"
# shellcheck source=/dev/null
source "${GITROOT}/dev/env/scripts/lib.sh"

log "Creating rhacs-registry image pull secret in namespace ${STACKROX_OPERATOR_NAMESPACE}"
print_pull_secret "rhacs-registry" "$(composite_registry_auth)" | $KUBECTL -n "$STACKROX_OPERATOR_NAMESPACE" apply -f -
log "Creating redhat-pull-secret image pull secret in namespace rhacs-vertical-pod-autoscaler"
print_pull_secret "redhat-pull-secret" "$(redhat_registry_auth)" | $KUBECTL -n "rhacs-vertical-pod-autoscaler" apply -f -
log
