#!/usr/bin/env bash

## This script assembles ImagePullSecrets for Quay.io as Kubernetes manifests ready for applying them to a cluster.

GITROOT="$(git rev-parse --show-toplevel)"
export GITROOT
# shellcheck source=/dev/null
source "${GITROOT}/dev/env/scripts/lib.sh"

registry="quay.io"

log "Creating rhacs-registry image pull secret in namespace ${STACKROX_OPERATOR_NAMESPACE}"
pull_secret.sh "rhacs-registry" "$registry" | $KUBECTL -n "$STACKROX_OPERATOR_NAMESPACE" apply -f -
log "Creating quay-ips image pull secret in namespace ${ACSCS_NAMESPACE}"
pull_secret.sh "quay-ips" "$registry" | $KUBECTL -n "$ACSCS_NAMESPACE" apply -f -
