// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package gitops

import (
	"context"
	"github.com/aws/aws-sdk-go-v2/service/secretsmanager"
	"sync"
)

// Ensure, that secretsManagerClientMock does implement secretsManagerClient.
// If this is not the case, regenerate this file with moq.
var _ secretsManagerClient = &secretsManagerClientMock{}

// secretsManagerClientMock is a mock implementation of secretsManagerClient.
//
//	func TestSomethingThatUsessecretsManagerClient(t *testing.T) {
//
//		// make and configure a mocked secretsManagerClient
//		mockedsecretsManagerClient := &secretsManagerClientMock{
//			GetSecretValueFunc: func(ctx context.Context, params *secretsmanager.GetSecretValueInput, optFns ...func(*secretsmanager.Options)) (*secretsmanager.GetSecretValueOutput, error) {
//				panic("mock out the GetSecretValue method")
//			},
//		}
//
//		// use mockedsecretsManagerClient in code that requires secretsManagerClient
//		// and then make assertions.
//
//	}
type secretsManagerClientMock struct {
	// GetSecretValueFunc mocks the GetSecretValue method.
	GetSecretValueFunc func(ctx context.Context, params *secretsmanager.GetSecretValueInput, optFns ...func(*secretsmanager.Options)) (*secretsmanager.GetSecretValueOutput, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetSecretValue holds details about calls to the GetSecretValue method.
		GetSecretValue []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params *secretsmanager.GetSecretValueInput
			// OptFns is the optFns argument value.
			OptFns []func(*secretsmanager.Options)
		}
	}
	lockGetSecretValue sync.RWMutex
}

// GetSecretValue calls GetSecretValueFunc.
func (mock *secretsManagerClientMock) GetSecretValue(ctx context.Context, params *secretsmanager.GetSecretValueInput, optFns ...func(*secretsmanager.Options)) (*secretsmanager.GetSecretValueOutput, error) {
	if mock.GetSecretValueFunc == nil {
		panic("secretsManagerClientMock.GetSecretValueFunc: method is nil but secretsManagerClient.GetSecretValue was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params *secretsmanager.GetSecretValueInput
		OptFns []func(*secretsmanager.Options)
	}{
		Ctx:    ctx,
		Params: params,
		OptFns: optFns,
	}
	mock.lockGetSecretValue.Lock()
	mock.calls.GetSecretValue = append(mock.calls.GetSecretValue, callInfo)
	mock.lockGetSecretValue.Unlock()
	return mock.GetSecretValueFunc(ctx, params, optFns...)
}

// GetSecretValueCalls gets all the calls that were made to GetSecretValue.
// Check the length with:
//
//	len(mockedsecretsManagerClient.GetSecretValueCalls())
func (mock *secretsManagerClientMock) GetSecretValueCalls() []struct {
	Ctx    context.Context
	Params *secretsmanager.GetSecretValueInput
	OptFns []func(*secretsmanager.Options)
} {
	var calls []struct {
		Ctx    context.Context
		Params *secretsmanager.GetSecretValueInput
		OptFns []func(*secretsmanager.Options)
	}
	mock.lockGetSecretValue.RLock()
	calls = mock.calls.GetSecretValue
	mock.lockGetSecretValue.RUnlock()
	return calls
}
