/*
 * Dinosaur Service Fleet Manager
 *
 * Dinosaur Service Fleet Manager APIs that are used by internal services e.g fleetshard operators.
 *
 * API version: 1.4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package private

// ManagedDinosaurDetailsMetadataAnnotations struct for ManagedDinosaurDetailsMetadataAnnotations
type ManagedDinosaurDetailsMetadataAnnotations struct {
	MasId          string `json:"mas/id"`
	MasPlacementId string `json:"mas/placementId"`
}
