#!/bin/bash

set -o pipefail

resource=${1}

if [[ -z "${resource}" ]]; then
    echo "Usage: $0 <URI> [ <curl flag> ... ]" >&2
    exit 1
fi

shift

# Normalize
resource=$(echo "$resource" | sed -e 's/^\///;')
FM_URL="${FM_URL:-http://localhost:8000}"

if [[ "$resource" != "metrics" ]]; then
  resource="api/$resource"
fi

curl -LH "Authorization: Bearer ${OCM_TOKEN}" "$FM_URL/${resource}" "$@" | jq .
