#!/bin/bash

set -o pipefail

TOKEN=${TOKEN:-$OCM_TOKEN}
resource=${1}

if [[ -z "${resource}" ]]; then
    echo "Usage: $0 <URI> [ <curl flag> ... ]" >&2
    exit 1
fi

shift

# Normalize
resource=$(echo "$resource" | sed -e 's/^\///;')
url="http://localhost:8000/api/${resource}"
echo "Requesting URL ${url} with parameters " "$@" "..." >&2
curl -LH "Authorization: Bearer ${TOKEN}" "$url" "$@" | jq .
