/*
 * Red Hat Advanced Cluster Security Service Fleet Manager Admin API
 *
 * Red Hat Advanced Cluster Security (RHACS) Service Fleet Manager Admin APIs that can be used by RHACS Managed Service Operations Team.
 *
 * API version: 0.0.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech). DO NOT EDIT.
package private

// CentralBillingChangeRequest Billing parameters to apply to the Central. Every field is written to the record as sent, so this request must carry the full desired state: a field omitted from the body is treated the same as an empty value and clears the stored value (it is not merged with the existing value).
type CentralBillingChangeRequest struct {
	Model          string `json:"model"`
	CloudAccountId string `json:"cloud_account_id"`
	CloudProvider  string `json:"cloud_provider"`
	Product        string `json:"product"`
}
