apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stackrox/acs-fleet-manager?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: |
      target_branch == "main"
      && (event == "push" || event == "pull_request")
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: acscs-main
    appstudio.openshift.io/component: acs-fleetshard-operator
    pipelines.appstudio.openshift.io/type: build
  name: acs-fleetshard-operator-on-push
  namespace: acscs-rhacs-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/acscs-rhacs-tenant/acscs-main/acs-fleetshard-operator:{{revision}}
  - name: dockerfile
    value: fleetshard-operator.Dockerfile
  - name: path-context
    value: .
  pipelineRef:
    name: base-acscs-pipeline
  taskRunTemplate:
    serviceAccountName: build-pipeline-acs-fleetshard-operator
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
