apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: acs-fleet-manager-e2e-tests
spec:
  description: |-
    This pipeline automates the process of running end-to-end tests for ACS Fleet Manager
    using a ROSA (Red Hat OpenShift Service on AWS) cluster. The pipeline provisions
    the ROSA cluster, installs fleet manager components, runs the tests
    and finally deprovisions the ROSA cluster.
  params:
    - name: SNAPSHOT
      description: 'The JSON string representing the snapshot of the application under test.'
      default: '{"components": [{"name":"test-app", "containerImage": "quay.io/example/repo:latest"}]}'
      type: string
  tasks:
    - name: generate-cluster-metadata
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/stackrox/konflux-tasks.git
          - name: revision
            value: yury/infractl
          - name: pathInRepo
            value: tasks/generate-infra-cluster-metadata-task.yaml
    - name: install-infractl
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/stackrox/konflux-tasks.git
          - name: revision
            value: yury/infractl
          - name: pathInRepo
            value: tasks/install-infractl-task.yaml
    - name: provision-cluster
      runAfter:
        - generate-cluster-metadata
        - install-infractl
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/stackrox/konflux-tasks.git
          - name: revision
            value: yury/infractl
          - name: pathInRepo
            value: tasks/create-infra-cluster-task.yaml
      params:
        - name: cluster-name
          value: $(tasks.generate-cluster-metadata.results.cluster-name)
        - name: flavor
          value: rosahcp
        - name: infractl-bin
          value: $(tasks.install-infractl.results.infractl-bin)
        - name: no-slack
          value: "true"
        - name: wait
          value: "true"
        - name: lifespan
          value: 2h
    - name: e2e-tests
      timeout: 2h
      runAfter:
        - provision-cluster
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
      taskSpec:
        params:
          - name: SNAPSHOT
        results:
          - name: TEST_OUTPUT
            description: Test output
        steps:
          - image: registry.redhat.io/openshift4/ose-cli:latest
            env:
              - name: SNAPSHOT
                value: $(params.SNAPSHOT)
            script: |
              dnf -y install jq

              echo -e "Example test task for the Snapshot:\n ${SNAPSHOT}"
              # Run custom tests for the given Snapshot here
              # After the tests finish, record the overall result in the RESULT variable
              RESULT="SUCCESS"

              # Output the standardized TEST_OUTPUT result in JSON form
              TEST_OUTPUT=$(jq -rc --arg date $(date -u --iso-8601=seconds) --arg RESULT "${RESULT}" --null-input \
                '{result: $RESULT, timestamp: $date, failures: 0, successes: 1, warnings: 0}')
              echo -n "${TEST_OUTPUT}" | tee $(results.TEST_OUTPUT.path)
  finally:
    - name: deprovision-cluster
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/stackrox/konflux-tasks.git
          - name: revision
            value: yury/infractl
          - name: pathInRepo
            value: tasks/delete-infra-cluster-task.yaml
      params:
        - name: cluster-name
          value: $(tasks.generate-cluster-metadata.results.cluster-name)
        - name: infractl-bin
          value: $(tasks.install-infractl.results.infractl-bin)
