/*
 * Red Hat Advanced Cluster Security Service Fleet Manager
 *
 * Red Hat Advanced Cluster Security (RHACS) Service Fleet Manager APIs that are used by internal services e.g fleetshard operators.
 *
 * API version: 1.4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech). DO NOT EDIT.
package private

// ArgoCdApplicationSource struct for ArgoCdApplicationSource
type ArgoCdApplicationSource struct {
	RepoURL        string                `json:"repoURL,omitempty"`
	TargetRevision string                `json:"targetRevision,omitempty"`
	Path           string                `json:"path,omitempty"`
	Chart          string                `json:"chart,omitempty"`
	Helm           ArgoCdApplicationHelm `json:"helm,omitempty"`
}
