/*
 * Red Hat Advanced Cluster Security Service Fleet Manager
 *
 * Red Hat Advanced Cluster Security (RHACS) Service Fleet Manager APIs that are used by internal services e.g fleetshard operators.
 *
 * API version: 1.4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech). DO NOT EDIT.
package private

// DataPlaneClusterUpdateStatusRequestAddons struct for DataPlaneClusterUpdateStatusRequestAddons
type DataPlaneClusterUpdateStatusRequestAddons struct {
	Id                  string `json:"id,omitempty"`
	Version             string `json:"version,omitempty"`
	SourceImage         string `json:"sourceImage,omitempty"`
	PackageImage        string `json:"packageImage,omitempty"`
	ParametersSHA256Sum string `json:"parametersSHA256Sum,omitempty"`
}
