/*
 * Red Hat Advanced Cluster Security Service Fleet Manager
 *
 * Red Hat Advanced Cluster Security (RHACS) Service Fleet Manager APIs that are used by internal services e.g fleetshard operators.
 *
 * API version: 1.4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech). DO NOT EDIT.
package private

// DataPlaneCentralStatus Schema of the status object for a Central
type DataPlaneCentralStatus struct {
	// The status conditions of a Central
	Conditions []DataPlaneClusterUpdateStatusRequestConditions `json:"conditions,omitempty"`
	// Routes created for a Central
	Routes []DataPlaneCentralStatusRoutes `json:"routes,omitempty"`
	// Map of Secrets created for a Central
	Secrets map[string]string `json:"secrets,omitempty"`
}
