/*
 * Red Hat Advanced Cluster Security Service Fleet Manager
 *
 * Red Hat Advanced Cluster Security (RHACS) Service Fleet Manager APIs that are used by internal services e.g fleetshard operators.
 *
 * API version: 1.4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech). DO NOT EDIT.
package private

// ArgoCdApplicationHelm struct for ArgoCdApplicationHelm
type ArgoCdApplicationHelm struct {
	PassCredentials         bool                                `json:"passCredentials,omitempty"`
	Parameters              []ArgoCdApplicationHelmParameter    `json:"parameters,omitempty"`
	FileParameters          []ArgoCdApplicatioHelmFileParameter `json:"fileParameters,omitempty"`
	ReleaseName             string                              `json:"releaseName,omitempty"`
	ValueFiles              []string                            `json:"valueFiles,omitempty"`
	IgnoreMissingValueFiles bool                                `json:"ignoreMissingValueFiles,omitempty"`
	SkipCrds                bool                                `json:"skipCrds,omitempty"`
	Values                  string                              `json:"values,omitempty"`
	ValuesObject            map[string]interface{}              `json:"valuesObject,omitempty"`
}
