/*
 * Red Hat Advanced Cluster Security Service Fleet Manager
 *
 * Red Hat Advanced Cluster Security (RHACS) Service Fleet Manager APIs that are used by internal services e.g fleetshard operators.
 *
 * API version: 1.4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech). DO NOT EDIT.
package private

// ManagedCentralAllOfSpecAdditionalAuthProviderOidc struct for ManagedCentralAllOfSpecAdditionalAuthProviderOidc
type ManagedCentralAllOfSpecAdditionalAuthProviderOidc struct {
	Issuer                    string `json:"issuer,omitempty"`
	CallbackMode              string `json:"callbackMode,omitempty"`
	ClientID                  string `json:"clientID,omitempty"`
	ClientSecret              string `json:"clientSecret,omitempty"`
	DisableOfflineAccessScope bool   `json:"disableOfflineAccessScope,omitempty"`
}
