/*
 * Red Hat Advanced Cluster Security Service Fleet Manager
 *
 * Red Hat Advanced Cluster Security (RHACS) Service Fleet Manager APIs that are used by internal services e.g fleetshard operators.
 *
 * API version: 1.4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package private

// DataPlaneCentralStatusRoutes Routes created for a Central
type DataPlaneCentralStatusRoutes struct {
	UiRouter   string `json:"uiRouter,omitempty"`
	DataRouter string `json:"dataRouter,omitempty"`
}
