/*
 * Red Hat Advanced Cluster Security Service Fleet Manager
 *
 * Red Hat Advanced Cluster Security (RHACS) Service Fleet Manager APIs that are used by internal services e.g fleetshard operators.
 *
 * API version: 1.4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech). DO NOT EDIT.
package private

// ArgoCdApplicationSpec struct for ArgoCdApplicationSpec
type ArgoCdApplicationSpec struct {
	Project              string                               `json:"project,omitempty"`
	Source               ArgoCdApplicationSource              `json:"source,omitempty"`
	Sources              []ArgoCdApplicationSource            `json:"sources,omitempty"`
	Destination          ArgoCdApplicationDestination         `json:"destination,omitempty"`
	Info                 []ArgoCdApplicationInfo              `json:"info,omitempty"`
	SyncPolicy           ArgoCdApplicationSyncPolicy          `json:"syncPolicy,omitempty"`
	IgnoreDifferences    []ArgoCdApplicationIgnoredDifference `json:"ignoreDifferences,omitempty"`
	RevisionHistoryLimit int32                                `json:"revisionHistoryLimit,omitempty"`
}
