/*
 * Red Hat Advanced Cluster Security Service Fleet Manager
 *
 * Red Hat Advanced Cluster Security (RHACS) Service Fleet Manager APIs that are used by internal services e.g fleetshard operators.
 *
 * API version: 1.4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech). DO NOT EDIT.
package private

// ArgoCdApplicationKustomize struct for ArgoCdApplicationKustomize
type ArgoCdApplicationKustomize struct {
	Version                   string                               `json:"version,omitempty"`
	NamePrefix                string                               `json:"namePrefix,omitempty"`
	NameSuffix                string                               `json:"nameSuffix,omitempty"`
	CommonLabels              map[string]string                    `json:"commonLabels,omitempty"`
	CommonAnnotations         map[string]string                    `json:"commonAnnotations,omitempty"`
	CommonAnnotationsEnvsubst bool                                 `json:"commonAnnotationsEnvsubst,omitempty"`
	Images                    []string                             `json:"images,omitempty"`
	Namespace                 string                               `json:"namespace,omitempty"`
	Replicas                  []ArgoCdApplicationKustomizeReplicas `json:"replicas,omitempty"`
}
