/*
 * Red Hat Advanced Cluster Security Service Fleet Manager
 *
 * Red Hat Advanced Cluster Security (RHACS) Service Fleet Manager APIs that are used by internal services e.g fleetshard operators.
 *
 * API version: 1.4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech). DO NOT EDIT.
package private

// ArgoCdApplicationSyncPolicyRetry struct for ArgoCdApplicationSyncPolicyRetry
type ArgoCdApplicationSyncPolicyRetry struct {
	Limit   int32                                   `json:"limit,omitempty"`
	Backoff ArgoCdApplicationSyncPolicyRetryBackoff `json:"backoff,omitempty"`
}
