apiVersion: "operators.coreos.com/v1alpha1"
kind: Subscription
metadata:
  name: compliance-operator
  namespace: openshift-compliance
spec:
  channel: stable
  installPlanApproval: Automatic
  name: openshift-compliance
  source: redhat-operators
  sourceNamespace: openshift-marketplace
