apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: acs-fleetshard
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - cloud.stackrox.io
    resources:
      - fleetshards
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cloud.stackrox.io
    resources:
      - fleetshards/finalizers
    verbs:
      - update
  - apiGroups:
      - cloud.stackrox.io
    resources:
      - fleetshards/status
    verbs:
      - get
      - patch
      - update
