apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: acs-fleetshard
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: acs-fleetshard
subjects:
  - kind: ServiceAccount
    name: acs-fleetshard-operator
    namespace: rhacs
