apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: acs-fleetshard
  namespace: "$ACSCS_NAMESPACE"
rules:
  - apiGroups:
      - operators.coreos.com
    resourceNames:
      - acs-fleetshard
    resources:
      - operatorconditions
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
