/*
 * Dinosaur Service Fleet Manager
 *
 * Dinosaur Service Fleet Manager APIs that are used by internal services e.g fleetshard operators.
 *
 * API version: 1.4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package private

// ManagedDinosaurDetailsSpecEndpointTls struct for ManagedDinosaurDetailsSpecEndpointTls
type ManagedDinosaurDetailsSpecEndpointTls struct {
	Cert string `json:"cert,omitempty"`
	Key  string `json:"key,omitempty"`
}
