apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhacs-external-dns
  namespace: "$ARGOCD_NAMESPACE"
spec:
  destination:
    namespace: external-dns-operator
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: "$ARGOCD_NAMESPACE"
        app.kubernetes.io/managed-by: "$ARGOCD_NAMESPACE"
    retry:
      limit: -1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  source:
    repoURL: https://github.com/stackrox/acscs-manifests
    targetRevision: HEAD
    path: external-dns
    helm:
      valuesObject:
        name: "$INFRASTRUCTURE_NAME"
        zones: [Z07321763RS4X0PD14EUT] # dev.acs.rhcloud.com Route53 zone
        region: us-east-1
