---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: terraforms.dataplane.acs.rhcloud.com
spec:
  group: dataplane.acs.rhcloud.com
  names:
    kind: Terraform
    listKind: TerraformList
    plural: terraforms
    singular: terraform
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Terraform is the Schema for the terraforms API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of Terraform
            type: object
            properties:
              fleetshardSync:
                type: object
                properties:
                  ocmToken:
                    type: string
                  fleetManagerEndpoint:
                    type: string
                  clusterId:
                    type: string
                  redHatSSO:
                    type: object
                    properties:
                      clientId:
                        type: string
                      clientSecret:
                        type: string
                    required:
                      - clientId
                      - clientSecret
                required:
                  - ocmToken
                  - fleetManagerEndpoint
                  - clusterId
                  - redHatSSO
              acsOperator:
                type: object
                properties:
                  enabled:
                    type: boolean
                  startingCSV:
                    type: string
                required:
                  - enabled
              observability:
                type: object
                properties:
                  enabled:
                    type: boolean
                  github:
                    type: object
                    properties:
                      accessToken:
                        type: string
                      repository:
                        type: string
                  observatorium:
                    type: object
                    properties:
                      gateway:
                        type: string
                      metricsClientId:
                        type: string
                      metricsSecret:
                        type: string
                required:
                  - enabled
            required:
              - fleetshardSync
              - acsOperator
              - observability
            x-kubernetes-preserve-unknown-fields: true
          status:
            description: Status defines the observed state of Terraform
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
