apiVersion: platform.stackrox.io/v1alpha1
kind: SecuredCluster
metadata:
  name: stackrox-secured-cluster-services
  namespace: {{ include "secured-cluster.namespace" . }}
  labels:
    # Only one ACS Operator should reconcile a single CR instance.
    # Label selector mechanism helps to specify which ACS Operator should reconcile the instance.
    # The dogfooding instance has to be reconciled only by operator with `rhacs.redhat.com/selector=dogfooding` label selector.
    rhacs.redhat.com/selector: dogfooding
spec:
  {{- if .Values.pullSecret }}
  imagePullSecrets:
  - name: {{ .Values.pullSecret }}
  {{- end }}
  clusterName: {{ required "clusterName is required when secured-cluster is enabled" .Values.clusterName }}
  centralEndpoint: {{ required "centralEndpoint is required when secured-cluster is enabled" .Values.centralEndpoint }}
  admissionControl:
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
  sensor:
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
  perNode:
    collector:
      resources:
        requests:
          memory: 100Mi
          cpu: 100m
    compliance:
      resources:
        requests:
          memory: 100Mi
          cpu: 100m
