apiVersion: platform.stackrox.io/v1alpha1
kind: SecuredCluster
metadata:
  name: stackrox-secured-cluster-services
  namespace: {{ include "secured-cluster.namespace" . }}
  labels:
    # Only one ACS Operator should reconcile a single CR instance.
    # Label selector mechanism helps to specify which ACS Operator should reconcile the instance.
    # The dogfooding instance has to be reconciled only by operator with `rhacs.redhat.com/selector=dogfooding` label selector.
    rhacs.redhat.com/selector: dogfooding
spec:
  {{- if .Values.pullSecret }}
  imagePullSecrets:
  - name: {{ .Values.pullSecret }}
  {{- end }}
  clusterName: {{ required "clusterName is required when secured-cluster is enabled" .Values.clusterName }}
  centralEndpoint: {{ required "centralEndpoint is required when secured-cluster is enabled" .Values.centralEndpoint }}
  admissionControl:
    {{- if .Values.admissionControl.resources }}
    resources: {{ toYaml .Values.admissionControl.resources | nindent 6 }}
    {{- end }}
    {{- if .Values.admissionControl.tolerations }}
    tolerations: {{ toYaml .Values.admissionControl.tolerations | nindent 6 }}
    {{- end }}
    {{- if .Values.admissionControl.nodeSelector }}
    nodeSelector: {{ toYaml .Values.admissionControl.nodeSelector | nindent 6 }}
    {{- end }}
  sensor:
    {{- if .Values.sensor.resources }}
    resources: {{ toYaml .Values.sensor.resources | nindent 6 }}
    {{- end }}
    {{- if .Values.sensor.tolerations }}
    tolerations: {{ toYaml .Values.sensor.tolerations | nindent 6 }}
    {{- end }}
    {{- if .Values.sensor.nodeSelector }}
    nodeSelector: {{ toYaml .Values.sensor.nodeSelector | nindent 6 }}
    {{- end }}
  perNode:
    collector:
      {{- if .Values.collector.resources }}
      resources: {{ toYaml .Values.collector.resources | nindent 8 }}
      {{- end }}
      {{- if .Values.collector.collection }}
      collection: {{ .Values.collector.collection | quote }}
      {{- end }}
    compliance:
      {{- if .Values.compliance.resources }}
      resources: {{ toYaml .Values.compliance.resources | nindent 8 }}
      {{- end }}
    nodeInventory:
      {{- if .Values.nodeInventory.resources }}
      resources: {{ toYaml .Values.nodeInventory.resources | nindent 8 }}
      {{- end }}

  scanner:
    {{- if .Values.scanner.scannerComponent }}
    scannerComponent: {{ .Values.scanner.scannerComponent }}
    {{- end }}
    analyzer:
      {{- if .Values.scanner.analyzer.resources }}
      resources: {{ toYaml .Values.scanner.analyzer.resources | nindent 8 }}
      {{- end }}
      {{- if .Values.scanner.analyzer.tolerations }}
      tolerations: {{ toYaml .Values.scanner.analyzer.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.scanner.analyzer.nodeSelector }}
      nodeSelector: {{ toYaml .Values.scanner.analyzer.nodeSelector | nindent 8 }}
      {{- end }}
    db:
      {{- if .Values.scanner.db.resources }}
      resources: {{ toYaml .Values.scanner.db.resources | nindent 8 }}
      {{- end }}
      {{- if .Values.scanner.db.tolerations }}
      tolerations: {{ toYaml .Values.scanner.db.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.scanner.db.nodeSelector }}
      nodeSelector: {{ toYaml .Values.scanner.db.nodeSelector | nindent 8 }}
      {{- end }}

  scannerV4:
    {{- if .Values.scannerV4.scannerComponent }}
    scannerComponent: {{ .Values.scannerV4.scannerComponent }}
    {{- end }}
    indexer:
      {{- if .Values.scannerV4.indexer.resources }}
      resources: {{ toYaml .Values.scannerV4.indexer.resources | nindent 8 }}
      {{- end }}
      {{- if .Values.scannerV4.indexer.tolerations }}
      tolerations: {{ toYaml .Values.scannerV4.indexer.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.scannerV4.indexer.nodeSelector }}
      nodeSelector: {{ toYaml .Values.scannerV4.indexer.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.scannerV4.indexer.scaling }}
      scaling: {{ toYaml .Values.scannerV4.indexer.scaling | nindent 8 }}
      {{- end }}

    db:
      {{- if .Values.scannerV4.db.resources }}
      resources: {{ toYaml .Values.scannerV4.db.resources | nindent 8 }}
      {{- end }}
      {{- if .Values.scannerV4.db.tolerations }}
      tolerations: {{ toYaml .Values.scannerV4.db.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.scannerV4.db.nodeSelector }}
      nodeSelector: {{ toYaml .Values.scannerV4.db.nodeSelector | nindent 8 }}
      {{- end }}
