/*
 * Red Hat Advanced Cluster Security Service Fleet Manager
 *
 * Red Hat Advanced Cluster Security (RHACS) Service Fleet Manager is a Rest API to manage instances of ACS components.
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package public

// List struct for List
type List struct {
	Kind           string `json:"kind"`
	NextPageCursor string `json:"next_page_cursor,omitempty"`
	Size           int32  `json:"size"`
}
