apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:openshift:leader-locking-openshift-route-controller-manager
  namespace: openshift-route-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: system:openshift:leader-locking-openshift-route-controller-manager
subjects:
  - kind: ServiceAccount
    name: route-controller-manager-sa
    namespace: openshift-route-controller-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:openshift:extension-apiserver-authentication-reader-openshift-route-controller-manager
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - kind: ServiceAccount
    name: route-controller-manager-sa
    namespace: openshift-route-controller-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:openshift:sa-creating-route-controller-manager
  namespace: openshift-infra
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: system:openshift:sa-creating-route-controller-manager
subjects:
  - kind: ServiceAccount
    name: route-controller-manager-sa
    namespace: openshift-route-controller-manager
