apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: route-controller-manager
    route-controller-manager: "true"
  name: route-controller-manager
  namespace: openshift-route-controller-manager
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: route-controller-manager
      route-controller-manager: "true"
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: route-controller-manager
        route-controller-manager: "true"
      name: route-controller-manager
    spec:
      containers:
        - command:
            - route-controller-manager
            - start
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          image: registry.redhat.io/openshift4/openshift-route-controller-manager-rhel8@sha256:d0fd1e8864285d2f9c5b6a9194607f35eeace86d8bfedfff964bd69dd9c1cb80
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: healthz
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: route-controller-manager
          ports:
            - containerPort: 8443
              protocol: TCP
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: healthz
              port: 8443
              scheme: HTTPS
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: FallbackToLogsOnError
      serviceAccountName: route-controller-manager-sa
