apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: openshift-default
spec:
  controller: openshift.io/ingress-to-route
  parameters:
    apiGroup: operator.openshift.io
    kind: IngressController
    name: default
    scope: Cluster
