apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aggregator.fullname" . }}
  namespace: {{ include "aggregator.namespace" . }}
  labels:
    {{- include "aggregator.selectorLabels" . | nindent 4 }}
  annotations:
  {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- if .Values.customConfig }}
  vector.yaml: |
{{ tpl (toYaml .Values.customConfig) . | indent 4 }}
  {{- end }}
