apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aggregator.fullname" . }}
  namespace: {{ include "aggregator.namespace" . }}
  labels:
    {{- include "aggregator.selectorLabels" . | nindent 4 }}
  annotations:
  {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
