apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aggregator.fullname" . }}
  namespace: {{ include "aggregator.namespace" . }}
  labels:
    {{- include "aggregator.selectorLabels" . | nindent 4 }}
  annotations:
  {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
