version: "3"
services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-h",
          "localhost",
          "-U",
          "${POSTGRES_USER}",
          "-d",
          "${POSTGRES_DB}"
        ]
      interval: 1s
      timeout: 3s
      retries: 30
  fleet-manager-init:
    build: ${GITROOT}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ${GITROOT}/secrets:/secrets
      - ./config:/config
    entrypoint: /usr/local/bin/fleet-manager migrate --db-host-file=secrets/db.host.docker-compose
    environment:
      - OCM_ENV=integration
  fleet-manager:
    build: ${GITROOT}
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      fleet-manager-init:
        condition: service_completed_successfully
    volumes:
      - ${GITROOT}/secrets:/secrets
      - ./config:/config
      - ~/.kube/config:/root/.kube/config
    entrypoint:
      - /usr/local/bin/fleet-manager
      - serve
      - --db-host-file=secrets/db.host.docker-compose
      - --api-server-bindaddress=0.0.0.0:8000
  fleetshard-sync:
    build: ${GITROOT}
    depends_on:
      fleet-manager:
        condition: service_started
    volumes:
      - ${GITROOT}/secrets:/secrets
      - ./config:/config
      - ~/.kube/config:/kubeconfig
    environment:
      - OCM_TOKEN=${OCM_TOKEN}
      - KUBECONFIG=/kubeconfig
      - FLEET_MANAGER_ENDPOINT=http://fleet-manager:8000
      - CLUSTER_ID=test
      - RUNTIME_POLL_PERIOD=10s
    entrypoint:
      - /usr/local/bin/fleetshard-sync
