name: Periodic Retest Failed Konflux Builds

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  periodic-retest-builds:
    uses: stackrox/actions/.github/workflows/periodic-retest-konflux-builds.yml@v1
    permissions:
      pull-requests: write
      issues: write
      checks: read
      contents: read
    with:
      max_retries: 3
      retest_command: '/konflux-retest'
