apiVersion: v1
kind: Service
metadata:
  labels:
    application: fleet-manager
  name: fleet-manager
  namespace: "$ACSCS_NAMESPACE"
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
    - name: healthcheck
      port: 8083
      targetPort: 8083
    - name: metrics
      port: 8080
      targetPort: 8080
    - name: pprof
      port: 6060
      targetPort: 6060
  selector:
    application: fleet-manager
status:
  loadBalancer: {}
